version: "3.9"
services:
  db:
    image: postgres:10.5-alpine
    ports:
      - "45432:5432"
    volumes:
      - talentai_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=talentai_dev

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "45672:5672"

volumes:
  talentai_data: {}
