# Generated by Django 2.1.2 on 2018-10-15 12:32

from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations


GROUP_PERMISSIONS = {
    'Recruiters': (
        'view_agency',
        'change_agency',

        'add_candidate',
        'view_candidate',
        'change_candidate',
        'delete_candidate',

        'add_proposal',
        'view_proposal',
        'delete_proposal',

        'view_client',
        'view_job'
    ),
    'Talent Associates': (
        'view_client',
        'change_client',

        'add_job',
        'view_job',
        'change_job',
        'delete_job',

        'view_proposal',
        'change_proposal',

        'view_agency',
        'view_candidate'
    ),
    'Hiring Managers': (
        'view_client',

        'view_job',
        'change_job',
        'delete_job',

        'view_proposal',
        'change_proposal',

        'view_agency',
        'view_candidate'
    ),
}


def add_user_groups(apps, schema_editor):
    """Create default Groups and assign the Permissions."""
    db_alias = schema_editor.connection.alias

    # Create Permission objects
    emit_post_migrate_signal(0, False, db_alias)

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    groups = Group.objects.using(db_alias).bulk_create(
        [Group(name=group) for group in GROUP_PERMISSIONS]
    )
    for group in groups:
        perms = Permission.objects.using(db_alias).filter(
            codename__in=GROUP_PERMISSIONS[group.name]
        ).all()
        group.permissions.add(*perms)



def delete_user_groups(apps, schema_editor):
    """Delete default Groups."""
    db_alias = schema_editor.connection.alias

    Group = apps.get_model('auth', 'Group')
    Group.objects.using(db_alias).filter(name__in=GROUP_PERMISSIONS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_proposal'),
    ]

    operations = [
        migrations.RunPython(add_user_groups, delete_user_groups)
    ]
