# Generated by Django 2.1.2 on 2018-10-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='agencies',
            field=models.ManyToManyField(to='core.Agency'),
        ),
    ]
