# Generated by Django 2.1.2 on 2018-10-23 20:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_hiringmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='managers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
