# Generated by Django 2.1.2 on 2018-10-31 05:35

import django.contrib.postgres.fields.jsonb
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_job_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyRegistrationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('headers', django.contrib.postgres.fields.jsonb.JSONField()),
                ('name', models.CharField(max_length=128)),
                ('contact_full_name', models.CharField(max_length=128)),
                ('contact_email', models.EmailField(max_length=254)),
                ('created', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClientRegistrationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('headers', django.contrib.postgres.fields.jsonb.JSONField()),
                ('name', models.CharField(max_length=128)),
                ('contact_full_name', models.CharField(max_length=128)),
                ('contact_email', models.EmailField(max_length=254)),
                ('created', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='agencies',
            field=models.ManyToManyField(blank=True, to='core.Agency'),
        ),
        migrations.AlterField(
            model_name='job',
            name='managers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
