# Generated by Django 2.1.2 on 2018-10-31 07:49

from django.db import migrations, models


def set_user_emails(apps, schema_editor):
    User = apps.get_model('core', 'User')

    for user in User.objects.all():
        if not user.email:
            user.email = '{}@localhost'.format(user.username)
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_registration_requests'),
    ]

    operations = [
        migrations.RunPython(set_user_emails),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
