# Generated by Django 2.1.2 on 2018-10-31 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together={('job', 'candidate')},
        ),
    ]
