# Generated by Django 2.1.2 on 2018-11-10 11:21

import django.db.models.deletion
from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations, models

GROUP_PERMISSIONS = {
    'Recruiters': (
        'view_contract',
    ),
    'Talent Associates': (
        'add_contract',
        'view_contract',
        'change_contract',
        'delete_contract'
    ),
    'Hiring Managers': (
        'view_contract',
    ),
}


def add_contract_permissions(apps, schema_editor):
    """Assign Contract Permissions."""
    db_alias = schema_editor.connection.alias

    # Create Permission objects
    emit_post_migrate_signal(0, False, db_alias)

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    groups = Group.objects.using(db_alias).filter(
        name__in=GROUP_PERMISSIONS
    ).all()
    for group in groups:
        perms = Permission.objects.using(db_alias).filter(
            codename__in=GROUP_PERMISSIONS[group.name]
        ).all()
        group.permissions.add(*perms)


def remove_contract_permissions(apps, schema_editor):
    """Remove Conract Permissions."""
    db_alias = schema_editor.connection.alias

    # Create Permission objects
    emit_post_migrate_signal(0, False, db_alias)

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    groups = Group.objects.using(db_alias).filter(
        name__in=GROUP_PERMISSIONS
    ).all()
    for group in groups:
        perms = Permission.objects.using(db_alias).filter(
            codename__in=GROUP_PERMISSIONS[group.name]
        ).all()
        group.permissions.remove(*perms)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_proposal_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Agency')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Client')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('client', 'agency')},
        ),
        migrations.RunPython(
            add_contract_permissions, remove_contract_permissions
        ),
    ]
