# Generated by Django 2.1.2 on 2018-11-11 18:00

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_contract'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('ja', 'Japanese')], default='ja', max_length=8),
        ),
    ]
