# Generated by Django 2.1.2 on 2018-11-28 17:37

import django.db.models.deletion
from django.db import migrations, models


LANGUAGE_CHOICES = ['en', 'ja']


def add_languages(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Language = apps.get_model('core', 'Language')

    for key in LANGUAGE_CHOICES:
        Language.objects.using(db_alias).update_or_create(language=key)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_candidatenote'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language', models.CharField(choices=[('en', 'English'), ('ja', 'Japanese')], max_length=16, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='fulltime',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Unknown', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_currency',
            field=models.CharField(choices=[('JPY', '¥'), ('USD', '$')], default='JPY', max_length=16),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_per',
            field=models.CharField(choices=[('year', 'Year'), ('month', 'Month'), ('week', 'Week'), ('day', 'Day'), ('hour', 'Hour')], default='year', max_length=16),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobquestion',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', related_query_name='question', to='core.Job'),
        ),
        migrations.AddField(
            model_name='job',
            name='required_languages',
            field=models.ManyToManyField(blank=True, to='core.Language'),
        ),
        migrations.RunPython(add_languages, migrations.RunPython.noop),
    ]
