# Generated by Django 2.1.2 on 2018-11-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_new_job_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='fulltime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='languages',
            field=models.ManyToManyField(blank=True, to='core.Language'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='local',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='location',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parttime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='salary_currency',
            field=models.CharField(choices=[('JPY', '¥'), ('USD', '$')], default='JPY', max_length=16),
        ),
        migrations.AddField(
            model_name='candidate',
            name='salary_per',
            field=models.CharField(choices=[('year', 'Year'), ('month', 'Month'), ('week', 'Week'), ('day', 'Day'), ('hour', 'Hour')], default='year', max_length=16),
        ),
    ]
