# Generated by Django 2.1.2 on 2018-12-09 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def remove_existing_requests(apps, schema_editor):
    for n in ['AgencyRegistrationRequest', 'ClientRegistrationRequest']:
        m = apps.get_model('core', n)
        m.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_candidate_fields'),
    ]

    operations = [
        migrations.RunPython(remove_existing_requests, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='agencyregistrationrequest',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='agencyregistrationrequest',
            name='contact_full_name',
        ),
        migrations.RemoveField(
            model_name='clientregistrationrequest',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='clientregistrationrequest',
            name='contact_full_name',
        ),
        migrations.AddField(
            model_name='agencyregistrationrequest',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientregistrationrequest',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RunPython(
            migrations.RunPython.noop, remove_existing_requests
        ),
    ]
