# Generated by Django 2.1.2 on 2018-12-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_update_reg_requests'),
    ]

    operations = [
        migrations.RenameField('job', 'enabled', 'published'),
        migrations.AlterField(
            model_name='job',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
