# Generated by Django 2.1.2 on 2018-12-15 15:08

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0022_job_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('agency_proposed_candidate_for_job', '{actor.name} proposed {action_object.name} for "{target.title}"'), ('talent_assigned_manager_for_job', '{actor.full_name} assigned you to "{target.title}"'), ('client_created_contract', '{actor.name} created contract with your agency'), ('client_assigned_agency_for_job', '{actor.name} assigned your agency to "{target.title}"'), ('client_updated_job', '{actor.name} updated "{target.title}"'), ('client_approved_candidate', '{actor.name} approved {action_object.name} for "{target.title}"'), ('client_declined_candidate', '{actor.name} declined {action_object.name} for "{target.title}"')], max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('unread', models.BooleanField(default=True)),
                ('emailed', models.BooleanField(default=False)),
                ('actor_object_id', models.CharField(max_length=255)),
                ('action_object_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('target_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('action_object_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_action_object', to='contenttypes.ContentType')),
                ('actor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_actor', to='contenttypes.ContentType')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email_agency_proposed_candidate_for_job',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_client_approved_candidate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_client_assigned_agency_for_job',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_client_created_contract',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_client_updated_job',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_talent_assigned_manager_for_job',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caused_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_target', to='contenttypes.ContentType'),
        ),
    ]
