# Generated by Django 2.1.2 on 2019-01-25 18:04

import django.db.models.deletion
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_job_public_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('private_note', models.CharField(max_length=1024)),
                ('token', models.CharField(default=core.models.generate_invite_token, editable=False, max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Agency')),
            ],
        ),
    ]
