# Generated by Django 2.1.2 on 2019-01-30 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_proposal_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='email_domain',
            field=models.CharField(blank=True, help_text="Adding agency's email domain will allow recruiters to register without additional actions", max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='agencyregistrationrequest',
            name='via_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='public_uuid',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
    ]
