# Generated by Django 2.1.2 on 2019-02-10 11:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_user_activation'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='li_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
