# Generated by Django 2.1.2 on 2019-02-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_fix_notification_verb'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
