# Generated by Django 2.1.2 on 2019-02-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_agency_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
