# Generated by Django 2.1.7 on 2019-02-22 20:31

import django.db.models.deletion
from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations, models

STATUSES = [
    ['new', 'Submitted'],
    ['proceeding', 'CV Approved'],
    ['rejected', 'CV Declined'],
    ['proceeding', 'Interviewing'],
    ['proceeding', 'Final Interview'],
    ['proceeding', 'Offer Prep'],
    ['proceeding', 'Offer Sent'],
    ['closed', 'Offer Accepted'],
    ['closed', 'Offer Declined'],
    ['closed', 'Candidate Quits Process'],
]


def add_default_statuses(apps, schema_editor):
    """Add default proposal statuses."""
    db_alias = schema_editor.connection.alias

    emit_post_migrate_signal(0, False, db_alias)

    ProposalStatus = apps.get_model('core', 'ProposalStatus')
    ClientProposalStatus = apps.get_model('core', 'ClientProposalStatus')
    status_objects = []

    for status_order, (status_group, status) in enumerate(STATUSES, 1):
        status_objects.append(
            ProposalStatus.objects.create(
                group=status_group,
                status_en=status,
                default=True,
                default_order=status_order
            )
        )

    Client = apps.get_model('core', 'Client')

    for c in Client.objects.all():
        for s in status_objects:
            ClientProposalStatus.objects.create(
                client=c,
                status=s,
                order=s.default_order
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_job_recruiters'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProposalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Client')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ProposalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('new', 'New'), ('proceeding', 'Proceeding'), ('rejected', 'Rejected'), ('closed', 'Closed')], max_length=32)),
                ('status', models.CharField(max_length=128)),
                ('status_en', models.CharField(max_length=128, null=True)),
                ('status_ja', models.CharField(max_length=128, null=True)),
                ('default', models.BooleanField(default=False, help_text='This status will be added for each new client')),
                ('default_order', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='clientproposalstatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ProposalStatus'),
        ),
        migrations.RunPython(
            add_default_statuses, migrations.RunPython.noop
        ),
    ]
