# Generated by Django 2.1.7 on 2019-02-22 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_custom_proposal_statuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='approved',
        ),
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.ProposalStatus'),
            preserve_default=False,
        ),
    ]
