# Generated by Django 2.1.7 on 2019-02-26 01:39

import django.db.models.deletion
from django.db import migrations, models


def remove_notifications(apps, schema_editor):
    """Add default proposal statuses."""

    Notification = apps.get_model('core', 'Notification')
    Notification.objects.filter(
        verb__in=['client_approved_candidate', 'client_declined_candidate']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0037_add_proposal_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('object_object_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='clientproposalstatus',
            options={'ordering': ('order',), 'verbose_name_plural': 'Company proposal statuses'},
        ),
        migrations.AlterModelOptions(
            name='proposalstatus',
            options={'verbose_name_plural': 'Proposal statuses'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email_client_approved_candidate',
            new_name='email_client_changed_proposal_status',
        ),
        migrations.RunPython(
            remove_notifications, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('agency_proposed_candidate_for_job', '{actor.name} proposed {action_object.name} for "{target.title}"'), ('agency_proposed_candidate_for_job', '{actor.name} proposed {action_object.name} for "{target.title}"'), ('client_assigned_agency_for_job', '{actor.name} assigned your agency to "{target.title}"'), ('client_changed_proposal_status', '{actor.name} changed status of {action_object.name} to {status.status} for "{target.title}"'), ('client_created_contract', '{actor.name} created contract with your agency'), ('client_updated_job', '{actor.name} updated "{target.title}"'), ('talent_assigned_manager_for_job', '{actor.full_name} assigned you to "{target.title}"')], max_length=255),
        ),
        migrations.AddField(
            model_name='notificationobject',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_objects', to='core.Notification'),
        ),
        migrations.AddField(
            model_name='notificationobject',
            name='object_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
