# Generated by Django 2.1.7 on 2019-03-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_proposal_status_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
