# Generated by Django 2.1.7 on 2019-02-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_proposal_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='client_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
