# Generated by Django 2.1.7 on 2019-02-23 13:39

from django.db import migrations, models


SIMPLE_LANGUAGE_CHOICES = ['ja', 'en']
LANGUAGE_CHOICES = [
    'cmn', 'es', 'en', 'hi', 'ar', 'pt', 'bn', 'ru', 'ja', 'lah', 'de', 'jv',
    'wu', 'zlm', 'te', 'vi', 'ko', 'fr', 'mr', 'ta', 'ur', 'tr', 'it', 'yue',
    'th'
]
LEVEL_CHOICES = range(5)


def add_simple_languages(apps, schema_editor):
    """Create English and Japanese languages."""
    db_alias = schema_editor.connection.alias

    Language = apps.get_model('core', 'Language')

    for key in SIMPLE_LANGUAGE_CHOICES:
        Language.objects.using(db_alias).update_or_create(language=key)


def add_languages(apps, schema_editor):
    """Create 25 most spoken languages with levels."""
    db_alias = schema_editor.connection.alias

    Language = apps.get_model('core', 'Language')

    for lang in LANGUAGE_CHOICES:
        for level in LEVEL_CHOICES:
            Language.objects.using(db_alias).update_or_create(
                language=lang,
                level=level
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_proposal_client_note'),
    ]

    operations = [
        migrations.RunPython(
            migrations.RunPython.noop, add_simple_languages
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='job',
            name='required_languages',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('cmn', 'Mandarin Chinese'), ('es', 'Spanish'), ('en', 'English'), ('hi', 'Hindi'), ('ar', 'Arabic'), ('pt', 'Poruguese'), ('bn', 'Bengali'), ('ru', 'Russian'), ('ja', 'Japanese'), ('lah', 'Lahnda'), ('de', 'German'), ('jv', 'Javanese'), ('wu', 'Shanghainese'), ('zlm', 'Malay'), ('te', 'Telugu'), ('vi', 'Vietnamese'), ('ko', 'Korean'), ('fr', 'French'), ('mr', 'Marathi'), ('ta', 'Tamil'), ('ur', 'Urdu'), ('tr', 'Turkish'), ('it', 'Italian'), ('yue', 'Yue Chinese'), ('th', 'Thai')], max_length=16)),
                ('level', models.IntegerField(choices=[(0, 'Basic'), (1, 'Conversational'), (2, 'Business'), (3, 'Fluent'), (4, 'Native')], default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='language',
            unique_together={('language', 'level')},
        ),
        migrations.AddField(
            model_name='candidate',
            name='languages',
            field=models.ManyToManyField(blank=True, to='core.Language'),
        ),
        migrations.AddField(
            model_name='job',
            name='required_languages',
            field=models.ManyToManyField(blank=True, to='core.Language'),
        ),
        migrations.RunPython(
            add_languages, migrations.RunPython.noop
        ),
    ]
