# Generated by Django 2.1.7 on 2019-02-25 23:52

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='resume',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='cv',
            new_name='resume',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='salary_per',
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_company',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_location',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='employment_status',
            field=models.CharField(choices=[('notemployed', 'Not employed'), ('fulltime', 'Full time'), ('fixedterm', 'Fixed term'), ('temporary', 'Temporary')], default='notemployed', max_length=16),
        ),
        migrations.AddField(
            model_name='candidate',
            name='first_name_ja',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='candidate',
            name='github_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_name_ja',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='candidate',
            name='linkedin_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='candidate',
            name='potential_locations',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='candidate',
            name='salary_breakdon',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='candidate',
            name='twitter_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidate',
            name='website_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
