# Generated by Django 2.1.7 on 2019-03-04 21:03

from django.db import migrations, models


def fix_candidate_none_fields(apps, schema_editor):
    """Set Candidate email and phone to empty string to remove None's."""
    db_alias = schema_editor.connection.alias

    Candidate = apps.get_model('core', 'Candidate')

    Candidate.objects.using(db_alias).update(
        email=models.F('email') or '',
        phone=models.F('phone') or '',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_candidate_fields'),
    ]

    operations = [
        migrations.RunPython(
            fix_candidate_none_fields, migrations.RunPython.noop
        ),
    ]
