# Generated by Django 2.1.7 on 2019-03-03 07:54

from django.db import migrations, models


def add_job_position_values(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Job = apps.get_model('core', 'Job')
    for j in Job.objects.using(db_alias).all():
        j.position = j.title
        j.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_proposals_and_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='position',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.RunPython(
            migrations.RunPython.noop, add_job_position_values
        ),
        migrations.RemoveField(
            model_name='job',
            name='position',
        ),
    ]
