# Generated by Django 2.1.7 on 2019-03-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_update_notification_verb_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('agency_proposed_candidate_for_job', '{actor.name} proposed {action_object.name} for "{target.title}"'), ('agency_proposed_candidate_for_job', '{actor.name} proposed {action_object.name} for "{target.title}"'), ('client_assigned_agency_for_job', '{actor.name} assigned your agency to "{target.title}"'), ('client_assigned_recruiter_for_job', '{actor.name} assigned you to "{target.title}"'), ('client_changed_proposal_status', '{actor.name} changed status of {action_object.name} to {status.status} for "{target.title}"'), ('client_created_contract', '{actor.name} created contract with your agency'), ('client_updated_job', '{actor.name} updated "{target.title}"'), ('talent_assigned_manager_for_job', '{actor.full_name} assigned you to "{target.title}"')], max_length=255),
        ),
    ]
