# Generated by Django 2.1.7 on 2019-03-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_add_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_client_assigned_recruiter_for_job',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('agency_proposed_candidate_for_job', 'Agency submits a candidate for a job'), ('client_assigned_agency_for_job', 'Client assigns your agency to a job'), ('client_assigned_recruiter_for_job', 'Client assigns you to a job'), ('client_changed_proposal_status', 'Client changes status of a submitted candidate'), ('client_created_contract', 'Client creates a contract with your agency'), ('client_updated_job', 'Client updates a job'), ('talent_assigned_manager_for_job', 'Talent Associate assigns you to a job')], max_length=255),
        ),
    ]
