# Generated by Django 2.1.7 on 2019-03-13 11:09

from django.db import migrations


def remove_proposal_delete_permission(apps, schema_editor):
    """Remove Proposal Delete Permissions."""
    db_alias = schema_editor.connection.alias

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    p = Permission.objects.using(db_alias).filter(
        codename='delete_proposal'
    ).first()

    groups = Group.objects.using(db_alias).filter(
        permissions=p
    ).all()

    for group in groups:
        group.permissions.remove(p)


def add_proposal_delete_permission(apps, schema_editor):
    """Add Proposal Delete Permissions."""
    db_alias = schema_editor.connection.alias

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    p = Permission.objects.using(db_alias).filter(
        codename='delete_proposal'
    ).first()

    groups = Group.objects.using(db_alias).filter(name='Recruiters').all()
    for group in groups:
        group.permissions.add(p)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_candidate_current_position'),
    ]

    operations = [
        migrations.RunPython(
            remove_proposal_delete_permission, add_proposal_delete_permission
        ),
    ]