# Generated by Django 2.1.7 on 2019-03-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_remove_proposal_delete_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='candidate_requirements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='critical_factors',
            field=models.TextField(blank=True, default=''),
        ),
    ]
