# Generated by Django 2.1.7 on 2019-03-13 18:48
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def fill_proposal_created_by(apps, schema_editor):
    """Fill proposals' created_by field."""
    Proposal = apps.get_model('core', 'Proposal')
    Recruiter = apps.get_model('core', 'Recruiter')

    # doesn't work on latest commit, need to replace import with apps.get_model
    from reversion.models import Version

    for p in Proposal.objects.all():
        for v in Version.objects.get_for_object(p).order_by('id'):
            ok = (
                v.revision.user and
                hasattr(v.revision.user, 'recruiter') and
                v.revision.user.recruiter.agency_id == p.candidate.agency_id
            )

            if not ok:
                continue

            p.created_by_id = v.revision.user.id
            p.save()
            break
        else:
            r = Recruiter.objects.filter(agency_id=p.candidate.agency_id).first()

            if r:
                p.created_by_id = r.user_id
                p.save()
            else:
                raise Exception(
                    'Create a recruiter for {}'.format(p.candidate.agency_id)
                )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_job_candidate_requirements_and_critical_factors'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            fill_proposal_created_by, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='proposal',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_proposals', to=settings.AUTH_USER_MODEL),
        ),
    ]
