# Generated by Django 2.1.7 on 2019-03-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_proposal_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
