# Generated by Django 2.1.7 on 2019-03-20 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_data_to_new_field(apps, schema_editor):
    """Migrate data."""
    Job = apps.get_model('core', 'Job')
    JobRecruiter = apps.get_model('core', 'JobRecruiter')
    JobAgency = apps.get_model('core', 'JobAgency')

    for j in Job.objects.all():
        for u in j._recruiters.all():
            JobRecruiter.objects.create(job=j, user=u)

        for a in j.agencies.all():
            JobAgency.objects.create(job=j, agency=a)


def migrate_data_to_old_field(apps, schema_editor):
    """Migrate data."""
    Job = apps.get_model('core', 'Job')

    for j in Job.objects.all():
        for r in j._recruiters1.all():
            j._recruiters.add(r)

        for a in j.agencies1.all():
            j.agencies.add(a)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_jobfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Agency')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Job')),
            ],
        ),
        migrations.CreateModel(
            name='JobRecruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='_recruiters1',
            field=models.ManyToManyField(blank=True, related_name='recruiter_for_jobs1', through='core.JobRecruiter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='agencies1',
            field=models.ManyToManyField(blank=True, related_name='jobs1', through='core.JobAgency', to='core.Agency'),
        ),
        migrations.AlterUniqueTogether(
            name='jobrecruiter',
            unique_together={('job', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='jobagency',
            unique_together={('job', 'agency')},
        ),
        migrations.RunPython(
            migrate_data_to_new_field, migrate_data_to_old_field
        ),
        migrations.RemoveField(
            model_name='job',
            name='agencies',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='agencies1',
            new_name='agencies',
        ),
        migrations.RemoveField(
            model_name='job',
            name='_recruiters',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='_recruiters1',
            new_name='_recruiters',
        ),
        migrations.AlterField(
            model_name='job',
            name='_recruiters',
            field=models.ManyToManyField(blank=True,
                                         related_name='recruiter_for_jobs',
                                         through='core.JobRecruiter',
                                         to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='agencies',
            field=models.ManyToManyField(blank=True, through='core.JobAgency',
                                         to='core.Agency'),
        ),
    ]
