# Generated by Django 2.1.7 on 2019-03-20 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_add_created_at_update_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Agency')),
            ],
        ),
        migrations.AddField(
            model_name='recruiter',
            name='teams',
            field=models.ManyToManyField(blank=True, to='core.AgencyTeam'),
        ),
        migrations.AlterUniqueTogether(
            name='agencyteam',
            unique_together={('name', 'agency')},
        ),
    ]
