# Generated by Django 2.1.7 on 2019-03-22 12:45

import django.db.models.deletion
from django.conf import settings
from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations, models

GROUP_NAME = 'Agency Managers'
GROUP_PERMISSIONS = [
    'view_agency',
    'change_agency',

    'add_candidate',
    'view_candidate',
    'change_candidate',
    'delete_candidate',

    'add_proposal',
    'view_proposal',

    'view_client',
    'view_job'
]


def add_user_group(apps, schema_editor):
    """Create default Groups and assign the Permissions."""
    db_alias = schema_editor.connection.alias

    # Create Permission objects
    emit_post_migrate_signal(0, False, db_alias)

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    group = Group.objects.using(db_alias).create(name=GROUP_NAME)
    perms = Permission.objects.using(db_alias).filter(
        codename__in=GROUP_PERMISSIONS
    ).all()
    group.permissions.add(*perms)


def delete_user_group(apps, schema_editor):
    """Delete default Groups."""
    db_alias = schema_editor.connection.alias

    Group = apps.get_model('auth', 'Group')
    Group.objects.using(db_alias).filter(name=GROUP_NAME).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_agency_teams'),
    ]

    operations = [
        migrations.RunPython(add_user_group, delete_user_group),
        migrations.CreateModel(
            name='AgencyManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Agency')),
                ('teams', models.ManyToManyField(blank=True, to='core.AgencyTeam')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
