# Generated by Django 2.1.7 on 2019-03-29 10:50

import django.db.models.deletion
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations, models

OLD_ACTIVATION_ACTION = 'make_user_recruiter'
NEW_ACTIVATION_ACTION = 'make_user_agency_admin'
GROUP_NAME = 'Agency Administrators'
GROUP_PERMISSIONS = [
    'view_agency',
    'change_agency',

    'add_candidate',
    'view_candidate',
    'change_candidate',
    'delete_candidate',

    'add_proposal',
    'view_proposal',

    'view_client',
    'view_job'
]


def add_user_group(apps, schema_editor):
    """Create Agency Administrators group and assign the Permissions."""
    db_alias = schema_editor.connection.alias

    # Create Permission objects
    emit_post_migrate_signal(0, False, db_alias)

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    group = Group.objects.using(db_alias).create(name=GROUP_NAME)
    perms = Permission.objects.using(db_alias).filter(
        codename__in=GROUP_PERMISSIONS
    ).all()
    group.permissions.add(*perms)


def delete_user_group(apps, schema_editor):
    """Delete Agency Administrators group."""
    db_alias = schema_editor.connection.alias

    Group = apps.get_model('auth', 'Group')
    Group.objects.using(db_alias).filter(name=GROUP_NAME).delete()


def make_on_activation_action_agency_admin(apps, schema_editor):
    """Change on_activation_action to make Agency Admins."""
    db_alias = schema_editor.connection.alias

    User = get_user_model()
    User.objects.using(db_alias).filter(
        on_activation_action=OLD_ACTIVATION_ACTION
    ).update(
        on_activation_action=NEW_ACTIVATION_ACTION
    )


def make_on_activation_action_recruiter(apps, schema_editor):
    """Change on_activation_action to make Recruiters."""
    db_alias = schema_editor.connection.alias

    User = get_user_model()
    User.objects.using(db_alias).filter(
        on_activation_action=NEW_ACTIVATION_ACTION
    ).update(
        on_activation_action=OLD_ACTIVATION_ACTION
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_agencymanager'),
    ]

    operations = [
        migrations.RunPython(add_user_group, delete_user_group),
        migrations.CreateModel(
            name='AgencyAdministrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Agency')),
                ('teams', models.ManyToManyField(blank=True, to='core.AgencyTeam')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(
            make_on_activation_action_agency_admin,
            make_on_activation_action_recruiter
        ),
    ]
