# Generated by Django 2.1.7 on 2019-04-10 03:00

from django.db import migrations
from django.db.models import F
from django.db.models.functions import Length


def copy_location_to_current_location(apps, schema_editor):
    """Overwrite current location value if location is longer."""
    db_alias = schema_editor.connection.alias

    Candidate = apps.get_model('core', 'Candidate')

    Candidate.objects.using(db_alias).annotate(
        location_len=Length('location')
    ).filter(
        # Location field value is longer than current_location value
        location_len__gt=Length('current_location')
    ).update(
        current_location=F('location')
    )


def copy_current_location_to_location(apps, schema_editor):
    """Copy values of the current location field to the location field."""
    db_alias = schema_editor.connection.alias

    Candidate = apps.get_model('core', 'Candidate')

    Candidate.objects.using(db_alias).all().update(
        location=F('current_location')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_agencyadministrator'),
    ]

    operations = [
        migrations.RunPython(
            copy_location_to_current_location,
            copy_current_location_to_location
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='location',
        ),
    ]
