# Generated by Django 2.1.7 on 2019-04-14 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def note_to_comment(apps, schema_editor):
    """Migrate Proposal note to ProposalComment."""
    db_alias = schema_editor.connection.alias

    Proposal = apps.get_model('core', 'Proposal')
    ProposalComment = apps.get_model('core', 'ProposalComment')

    for p in Proposal.objects.using(db_alias).exclude(client_note='').all():

        author = p.job.client.talentassociate_set.first().user
        if not author:
            author = p.job.client.members.first()

        ProposalComment.objects.using(db_alias).create(
            author=author,
            proposal=p,
            text=p.client_note,
            public=False
        )


def comment_to_note(apps, schema_editor):
    """Migrate first ProposalComment without User to Proposal note."""
    db_alias = schema_editor.connection.alias

    User = apps.get_model('core', 'User')
    Proposal = apps.get_model('core', 'Proposal')

    for p in Proposal.objects.using(db_alias).all():
        members = User.objects.filter(
            models.Q(talentassociate__client=p.job.client) |
            models.Q(hiringmanager__client=p.job.client)
        )
        comment = p.proposalcomment_set.filter(author__in=members).order_by(
            'created_at'
        ).first()

        if comment:
            p.client_note = comment.text
            p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_add_proposal_status_client_declined'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_en', models.TextField(null=True)),
                ('text_ja', models.TextField(null=True)),
                ('public', models.BooleanField(default=False)),
                ('system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Proposal')),
                ('proposal_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ProposalStatus')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(note_to_comment, comment_to_note),
        migrations.RemoveField(
            model_name='proposal',
            name='client_note',
        ),
    ]
