# Generated by Django 2.1.7 on 2019-05-04 08:41

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_proposalcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_user_photo_upload_to),
        ),
    ]
