# Generated by Django 2.1.7 on 2019-05-02 00:53

from django.db import migrations, models

OLD_STATUSES = [
    ['new', 'Submitted'],
    ['proceeding', 'CV Approved'],
    ['rejected', 'CV Declined'],
    ['proceeding', 'Interviewing'],
    ['proceeding', 'Final Interview'],
    ['proceeding', 'Offer Prep'],
    ['proceeding', 'Offer Sent'],
    ['closed', 'Offer Accepted'],
    ['closed', 'Offer Declined'],
    ['closed', 'Candidate Quits Process'],
    ['closed', 'Client declined'],
]

NEW_STATUSES = [
    ['new', 'Submitted'],
    ['approved', 'CV Approved'],
    ['rejected', 'CV Declined'],
    ['interviewing', 'Interviewing'],
    ['interviewing', 'Final Interview'],
    # "Offer Prep" shouldn't be counted as offer stage for KPI
    # can be updated later
    ['proceeding', 'Offer Prep'],
    ['offer', 'Offer Sent'],
    ['offer_accepted', 'Offer Accepted'],
    ['offer_declined', 'Offer Declined'],
    ['candidate_quit', 'Candidate Quits Process'],
    ['closed', 'Client declined'],
]


def update_default_proposal_statuses_groups(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    ProposalStatus = apps.get_model('core', 'ProposalStatus')

    for (new_group, status) in NEW_STATUSES:
        s = ProposalStatus.objects.using(db_alias).filter(
            default=True, status_en=status
        ).first()
        s.group = new_group
        s.save()


def revert_default_proposal_statuses_groups(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    ProposalStatus = apps.get_model('core', 'ProposalStatus')

    for (new_group, status) in OLD_STATUSES:
        s = ProposalStatus.objects.using(db_alias).filter(
            default=True, status_en=status
        ).first()
        s.group = new_group
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalstatus',
            name='group',
            field=models.CharField(
                choices=[('new', 'New'), ('proceeding', 'Proceeding'),
                         ('approved', 'CV approved'),
                         ('rejected', 'CV rejected'),
                         ('interviewing', 'Interviewing'), ('offer', 'Offer'),
                         ('offer_accepted', 'Offer Accepted'),
                         ('offer_declined', 'Offer Declined'),
                         ('candidate_quit', 'Candidate Quits Process'),
                         ('closed', 'Closed')], max_length=32),
        ),
        migrations.RunPython(
            update_default_proposal_statuses_groups,
            revert_default_proposal_statuses_groups
        )
    ]
