# Generated by Django 2.1.7 on 2019-05-09 09:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_update_default_proposal_statuses_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='zoho_auth_token',
            field=models.CharField(blank=True, help_text='Can be generated on this page:\nhttps://accounts.zoho.com/apiauthtoken/create?SCOPE=ZohoRecruit/recruitapi', max_length=32),
        ),
        migrations.AddField(
            model_name='candidate',
            name='zoho_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='zoho_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('agency', 'linkedin_slug'), ('agency', 'zoho_id')},
        ),
    ]
