# Generated by Django 2.1.7 on 2019-04-24 15:16

import django.db.models.deletion
import gfklookupwidget.fields
from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations, models

GROUP_NAMES = ['Talent Associates', 'Hiring Managers']
GROUP_PERMISSIONS = [
    'add_candidate',
    'change_candidate',
    'delete_candidate',

    'add_proposal',
]


def add_candidate_permissions(apps, schema_editor):
    """Add add, change and delete Candidate perms to Client Users."""
    db_alias = schema_editor.connection.alias

    # Create Permission objects
    emit_post_migrate_signal(0, False, db_alias)

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    for group_name in GROUP_NAMES:
        group = Group.objects.using(db_alias).get(name=group_name)
        perms = Permission.objects.using(db_alias).filter(
            codename__in=GROUP_PERMISSIONS
        ).all()
        group.permissions.add(*perms)


def remove_candidate_permissions(apps, schema_editor):
    """Remove add, change and delete Candidate perms from Client Users."""
    db_alias = schema_editor.connection.alias

    # Create Permission objects
    emit_post_migrate_signal(0, False, db_alias)

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    for group_name in GROUP_NAMES:
        group = Group.objects.using(db_alias).get(name=group_name)
        perms = Permission.objects.using(db_alias).filter(
            codename__in=GROUP_PERMISSIONS
        ).all()
        group.permissions.remove(*perms)



class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0070_zoho_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Agency'),
        ),
        migrations.RunPython(
            add_candidate_permissions,
            remove_candidate_permissions
        ),
        migrations.AddField(
            model_name='candidate',
            name='org_content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'agency')), models.Q(('app_label', 'core'), ('model', 'client')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='org_id',
            field=gfklookupwidget.fields.GfkLookupField(null=True),
        ),
    ]
