# Generated by Django 2.1.7 on 2019-04-24 15:22

from django.contrib.contenttypes.models import ContentType
from django.db import migrations


def agency_to_organization(apps, schema_editor):
    """Migrate Candidate agency field to organization."""
    db_alias = schema_editor.connection.alias

    Candidate = apps.get_model('core', 'Candidate')
    agency_content_type = ContentType.objects.using(db_alias).get(
        app_label='core', model='agency'
    )

    for c in Candidate.objects.using(db_alias).all():
        c.org_content_type_id = agency_content_type.pk
        c.org_id = c.agency.pk
        c.save()


def organization_to_agency(apps, schema_editor):
    """Delete Client Candidates, migrate organization field to agency."""
    db_alias = schema_editor.connection.alias

    Agency = apps.get_model('core', 'Agency')
    Candidate = apps.get_model('core', 'Candidate')
    agency_content_type = ContentType.objects.using(db_alias).get(
        app_label='core', model='agency'
    )

    Candidate.objects.using(db_alias).exclude(
        org_content_type_id=agency_content_type.pk
    ).delete()

    for c in Candidate.objects.using(db_alias).all():
        c.agency_id = Agency.objects.get(pk=c.org_id).pk
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_candidate_organization'),
    ]

    operations = [
        migrations.RunPython(
            agency_to_organization,
            organization_to_agency
        ),
    ]
