# Generated by Django 2.1.7 on 2019-04-24 15:45

import gfklookupwidget.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_candidate_agency_remove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='org_id',
            field=gfklookupwidget.fields.GfkLookupField(null=False),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('org_content_type', 'org_id', 'zoho_id'), ('org_content_type', 'org_id', 'linkedin_slug')},
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='agency',
        ),
    ]
