# Generated by Django 2.1.7 on 2019-05-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_candidate_unique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_agency_proposed_candidate_for_job',
            new_name='email_candidate_proposed_for_job',
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('candidate_proposed_for_job', 'Candidate submitted for a job'), ('client_assigned_agency_for_job', 'Client assigns your agency to a job'), ('client_assigned_recruiter_for_job', 'Client assigns you to a job'), ('client_changed_proposal_status', 'Client changes status of a submitted candidate'), ('client_created_contract', 'Client creates a contract with your agency'), ('client_updated_job', 'Client updates a job'), ('proposal_moved', 'Candidate is reallocated to a different job'), ('talent_assigned_manager_for_job', 'Talent Associate assigns you to a job')], max_length=255),
        ),
    ]
