# Generated by Django 2.1.7 on 2019-06-05 05:49

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_candidate_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='description',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='agency',
            name='industries',
            field=models.TextField(blank=True, help_text='Comma separated'),
        ),
        migrations.AddField(
            model_name='agency',
            name='logo',
            field=models.FileField(blank=True, help_text='png, svg', null=True, upload_to=core.models.get_agency_logo_upload_to, validators=[core.models.validate_file_image]),
        ),
        migrations.AddField(
            model_name='agency',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
