# Generated by Django 2.1.7 on 2019-06-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_agecy_info_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume_thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
