# Generated by Django 2.2.2 on 2019-06-16 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_thumbnails_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core.Proposal')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ProposalStatus')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
