# Generated by Django 2.1.7 on 2019-06-18 09:13

from django.db import migrations, models
from django.db.models import F


def set_job_published_at(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Job = apps.get_model('core', 'Job')
    Job.objects.using(db_alias).filter(
        published=True
    ).update(
        published_at=F('created_at')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_proposal_status_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            set_job_published_at, migrations.RunPython.noop
        ),
    ]
