# Generated by Django 2.1.7 on 2019-05-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_job_published_at_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='zoho_auth_token',
            field=models.CharField(blank=True, help_text='Can be generated on this page:\nhttps://accounts.zoho.com/apiauthtoken/create?SCOPE=ZohoRecruit/recruitapi', max_length=32),
        ),
    ]
