# Generated by Django 2.2.2 on 2019-06-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_job_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('Placement type', 'Placement type'), ('Function focus', 'Function focus'), ('Industry focus', 'Industry focus')], max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('title_en', models.CharField(max_length=64, null=True)),
                ('title_ja', models.CharField(max_length=64, null=True)),
            ],
            options={
                'verbose_name_plural': 'agency categories',
                'ordering': ('group', 'title_en'),
            },
        ),
        migrations.AddField(
            model_name='agency',
            name='categories',
            field=models.ManyToManyField(to='core.AgencyCategory'),
        ),
    ]
