# Generated by Django 2.2.2 on 2019-06-28 13:03

from django.db import migrations

DATA = {
    'Placement type': [
        'Executive search (retainer)',
        'Executive search (contingency)',
        'Permanent placement',
        'Direct contract (Keiyaku)',
        'Temp & Contract (Haken)',
        'Temp to perm (Shokai Yotei Haken)',
        'Outsourcing (Gyomu itaku)',
        'RPO',
        'New Grads',
        'Internship',
        'Others',
    ],
    'Function focus': [
        'Accounting & Finance',
        'Administration & Office Support',
        'Architecture & Construction',
        'Automobile',
        'Business Development',
        'Consulting',
        'Customer service',
        'Education / Training / Coaching',
        'Energy',
        'Engineering',
        'Finance Banking',
        'Government Affairs',
        'HR & Recruitment',
        'Hardware',
        'Healthcare',
        'Insurance',
        'IT',
        'Legal & Compliance',
        'Localization & Translation',
        'Logistics',
        'Management',
        'Manufacturing / Supply Chain',
        'Marketing, PR & Advertising',
        'Media, Art & Entertainment',
        'Operations',
        'Procurement',
        'Real Estate',
        'Retail, Fashion, Consumer Goods',
        'Sales - Retail Sales (B2C)',
        'Sales - Corporate Sales (B2B)',
        'Software',
        'Telecommunications',
        'Tourism, Travel & Hospitality',
    ],
    'Industry focus': [
        'Automobile, Aviation & Aerospace',
        'Banking & Financial Services',
        'Energy & Natural Resources',
        'Food & Beverage, FMCG',
        'Electronic Goods',
        'Healthcare / Pharmaceutical / Life Sciences',
        'Insurance',
        'IT, Technology, Digital, & Telecom',
        'Leisure, Hospitality, Restaurants, Travel & Tourism',
        'Manufacturing / Industrial',
        'Media, Communication, Agency',
        'Public Sector',
        'Real Estate, Property & Construction',
        'Retail, Fashion, Luxury, Consumer Goods',
        'Services ',
        'Transportation, Shipping, Logistics',
    ],
}


def add_default_agency_categories(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    AgencyCategory = apps.get_model('core', 'AgencyCategory')

    for gorup, items in DATA.items():
        for title in sorted(items):
            AgencyCategory.objects.using(db_alias).update_or_create(
                group=gorup,
                title_en=title.strip()
            )


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0083_agency_categories'),
    ]

    operations = [
        migrations.RunPython(
            add_default_agency_categories, migrations.RunPython.noop
        ),
    ]
