# Generated by Django 2.2.2 on 2019-07-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_add_default_agency_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='industries',
        ),
        migrations.AddField(
            model_name='agency',
            name='name_ja',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='client',
            name='name_ja',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
