# Generated by Django 2.2.2 on 2019-07-11 07:44

from django.db import migrations

DATA = {
    'Placement type': [
        'Direct contract (Keiyaku)',
        'Executive search (contingency)',
        'Executive search (retainer)',
        'Internship',
        'New Grads',
        'Others',
        'Outsourcing (Gyomu itaku)',
        'Permanent placement',
        'RPO',
        'Temp & Contract (Haken)',
        'Temp to perm (Shokai Yotei Haken)'
    ],
    'Function focus': [
        'Accounting & Finance',
        'Administration & Office Support',
        'Business Development',
        'Consulting',
        'Customer Service',
        'Education / Training / Coaching',
        'Engineering',
        'Government Affairs',
        'HR & Recruitment',
        'IT',
        'Legal & Compliance',
        'Localization & Translation',
        'Logistics',
        'Management',
        'Manufacturing / Supply Chain',
        'Marketing / PR & Advertising',
        'Operations',
        'Procurement',
        'Quality',
        'R&D',
        'Sales - Corporate Sales (B2B)',
        'Sales - Retail Sales (B2C)'
    ],
    'Industry focus': [
        'Architecture & Construction',
        'Automobile / Aviation & Aerospace',
        'Banking & Financial Services',
        'Consulting',
        'Education / Training / Coaching',
        'Electronic Goods',
        'Energy & Natural Resources',
        'Fintech',
        'Food & Beverage / FMCG',
        'Hardware',
        'Healthcare / Pharmaceutical / Life Sciences',
        'IT / Technology/ Digital & Telecom',
        'Insurance',
        'Legal & Compliance',
        'Leisure / Hospitality / Restaurants / Travel & Tourism',
        'Manufacturing / Industrial',
        'Media / Art & Entertaiment / Communication / Agency',
        'Public Sector',
        'Real Estate / Property & Construction',
        'Recruitment',
        'Retail / Fashion / Luxury / Consumer Goods',
        'Services',
        'Software',
        'Transportation / Shipping / Logistics'
    ]
}


def add_default_agency_categories(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    AgencyCategory = apps.get_model('core', 'AgencyCategory')
    Agency = apps.get_model('core', 'Agency')
    Agency.categories.through.objects.all().delete()
    AgencyCategory.objects.all().delete()

    for gorup, items in DATA.items():
        for title in sorted(items):
            AgencyCategory.objects.using(db_alias).update_or_create(
                group=gorup,
                title_en=title.strip()
            )


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0086_job_closed_at'),
    ]

    operations = [
        migrations.RunPython(
            add_default_agency_categories, migrations.RunPython.noop
        ),
    ]
