# Generated by Django 2.2.2 on 2019-07-14 11:32

from django.db import migrations, models
import django.db.models.deletion
import gfklookupwidget.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0087_update_agency_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('org_id', gfklookupwidget.fields.GfkLookupField()),
                ('org_content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'agency')), models.Q(('app_label', 'core'), ('model', 'client')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'unique_together': {('name', 'org_content_type', 'org_id')},
            },
        ),
        migrations.AddField(
            model_name='agencyadministrator',
            name='new_teams',
            field=models.ManyToManyField(blank=True, to='core.Team'),
        ),
        migrations.AddField(
            model_name='agencymanager',
            name='new_teams',
            field=models.ManyToManyField(blank=True, to='core.Team'),
        ),
        migrations.AddField(
            model_name='hiringmanager',
            name='teams',
            field=models.ManyToManyField(blank=True, to='core.Team'),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='new_teams',
            field=models.ManyToManyField(blank=True, to='core.Team'),
        ),
        migrations.AddField(
            model_name='talentassociate',
            name='teams',
            field=models.ManyToManyField(blank=True, to='core.Team'),
        ),
    ]
