# Generated by Django 2.2.2 on 2019-07-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_auto_20190714_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencyadministrator',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='agencymanager',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='teams',
        ),
        migrations.RenameField(
            model_name='agencyadministrator',
            old_name='new_teams',
            new_name='teams',
        ),
        migrations.RenameField(
            model_name='agencymanager',
            old_name='new_teams',
            new_name='teams',
        ),
        migrations.RenameField(
            model_name='recruiter',
            old_name='new_teams',
            new_name='teams',
        ),
        migrations.DeleteModel(
            name='AgencyTeam',
        ),
    ]
