# Generated by Django 2.2.2 on 2019-07-18 14:33

import django.db.models.deletion
from django.db import migrations, models


def add_default_job_categories(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Agency = apps.get_model('core', 'Agency')
    AgencyCategory = apps.get_model('core', 'AgencyCategory')
    JobCategory = apps.get_model('core', 'JobCategory')

    acs = AgencyCategory.objects.using(db_alias).filter(
        group='Function focus'
    ).order_by(
        'title_en'
    ).all()

    for ac in acs:
        jc, _ = JobCategory.objects.using(db_alias).update_or_create(
            title_en=ac.title_en
        )

        for x in Agency.categories.through.objects.using(db_alias).filter(agencycategory_id=ac.id):
            x.agency.function_focus.add(jc)

    AgencyCategory.objects.using(db_alias).filter(
        group='Function focus'
    ).delete()


def migrate_job_categories(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Agency = apps.get_model('core', 'Agency')
    AgencyCategory = apps.get_model('core', 'AgencyCategory')
    JobCategory = apps.get_model('core', 'JobCategory')

    jcs = JobCategory.objects.using(db_alias).order_by(
        'title_en'
    ).all()

    for jc in jcs:
        ac, _ = AgencyCategory.objects.using(db_alias).update_or_create(
            group='Function focus',
            title_en=jc.title_en
        )

        for x in Agency.function_focus.through.objects.using(db_alias).filter(jobcategory_id=jc.id):
            x.agency.categories.add(ac)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('title_en', models.CharField(max_length=64, null=True)),
                ('title_ja', models.CharField(max_length=64, null=True)),
            ],
            options={
                'verbose_name_plural': 'Job Categories (Agency Function Focus)',
                'ordering': ('title_en',),
            },
        ),
        migrations.AddField(
            model_name='agency',
            name='function_focus',
            field=models.ManyToManyField(to='core.JobCategory'),
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='core.JobCategory'),
        ),
        migrations.AlterField(
            model_name='agencycategory',
            name='group',
            field=models.CharField(
                choices=[('Placement type', 'Placement type'),
                         ('Industry focus', 'Industry focus')], max_length=64),
        ),
        migrations.RunPython(
            add_default_job_categories, migrate_job_categories
        ),
    ]
