# Generated by Django 2.2.2 on 2019-07-23 13:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_candidate_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='li_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
