# Generated by Django 2.2.2 on 2019-07-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_auto_20190723_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonDeclineCandidateOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('text_en', models.CharField(max_length=255, null=True)),
                ('text_ja', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='proposal',
            name='decline_reasons',
            field=models.ManyToManyField(to='core.ReasonDeclineCandidateOption'),
        ),
    ]
