# Generated by Django 2.2.2 on 2019-08-26 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_update_submitted_proposal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='core.Candidate'),
        ),
    ]
