# Generated by Django 2.2.2 on 2019-09-02 09:31

from django.db import migrations, models

CURRENCY_TYPES = [
    ('JPY', '¥'),
    ('USD', '$'),
    ('EUR', '€'),
    ('CNY', '¥'),
    ('GBP', '£'),
    ('KRW', '₩'),
    ('INR', '₹'),
    ('CAD', '$'),
    ('HKD', '$'),
    ('BRL', 'R$')
]


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_candidate_add_related_field_proposals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='salary_currency',
            field=models.CharField(choices=CURRENCY_TYPES, default='JPY', max_length=16),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_currency',
            field=models.CharField(choices=CURRENCY_TYPES, default='JPY', max_length=16),
        ),
    ]
