# Generated by Django 2.2.2 on 2019-07-24 08:40
from django.conf import settings
from django.db import migrations, models


def initiate_contracts(apps, schema_editor):
    """Sets state to Initiated for alredy existing contracts"""
    Contract = apps.get_model('core', 'Contract')
    for contract in Contract.objects.all():
        contract.status = 'initiated'
        contract.save()


def revert_initiate_contracts(apps, schema_editor):
    pass    # do nothing


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_change_acceptable_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='agency',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name='contracts',
                to='core.Agency'
            ),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name='contracts',
                to='core.Client'
            ),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_agency_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_client_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='invite_duration_days',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='contract',
            name='end_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='fee_currency',
            field=models.CharField(
                choices=[
                    ('JPY', '¥'),
                    ('USD', '$'),
                    ('EUR', '€'),
                    ('CNY', '¥'),
                    ('GBP', '£'),
                    ('KRW', '₩'),
                    ('INR', '₹'),
                    ('CAD', '$'),
                    ('HKD', '$'),
                    ('BRL', 'R$')
                ],
                default='JPY',
                max_length=16
            ),
        ),
        migrations.AddField(
            model_name='contract',
            name='initial_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='start_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='fee_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Float number of percent in format: 00.00', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(
                choices=[
                    ('agency_invited', 'Agency Invited'),
                    ('pending', 'Pending'),
                    ('initiated', 'Initiated'),
                    ('rejected', 'Rejected'),
                    ('expired', 'Expired')
                ],
                default='agency_invited',
                max_length=16
            ),
        ),
        migrations.AddField(
            model_name='contract',
            name='duration',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='primary_contact',
            field=models.ForeignKey(null=True, on_delete=models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='primary_contact',
            field=models.ForeignKey(null=True, on_delete=models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_waiting_invite',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            initiate_contracts,
            revert_initiate_contracts
        )
    ]
