# Generated by Django 2.2.2 on 2019-09-17 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_notification_explicit_link'),
    ]

    operations = [
        migrations.RenameModel('JobRecruiter', 'JobAssignee'),
        migrations.RenameField('Job', '_recruiters', '_assignees'),
        migrations.AlterField(
            model_name='job',
            name='_assignees',
            field=models.ManyToManyField(blank=True,
                                         related_name='assigned_to_jobs',
                                         through='core.JobAssignee',
                                         to=settings.AUTH_USER_MODEL),
        ),
    ]
