# Generated by Django 2.2.5 on 2019-09-26 12:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_candidate_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_resume_upload_to),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume_thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=core.models.get_resume_thumbnail_upload_to),
        ),
        migrations.AlterField(
            model_name='jobfile',
            name='file',
            field=models.FileField(upload_to=core.models.get_jobfile_upload_to),
        ),
    ]
