# Generated by Django 2.2.5 on 2019-09-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_upload_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='stage',
            field=models.CharField(choices=[('longlist', 'Longlist'), ('shortlist', 'Shortlist')], default='shortlist', max_length=16),
        ),
    ]
