# Generated by Django 2.2.5 on 2019-10-02 14:51

from django.db import migrations, models


def apply_new_notification_type(apps, schema_editor):
    Notitification = apps.get_model('core', 'Notification')
    Notitification.objects.filter(
        verb='candidate_proposed_for_job'
    ).update(verb='candidate_shortlisted_for_job')


def revert_apply_new_notification_type(apps, schema_editor):
    Notitification = apps.get_model('core', 'Notification')
    Notitification.objects.filter(
        verb__in=['candidate_shortlisted_for_job',
                  'candidate_longlisted_for_job']
    ).update(verb='candidate_proposed_for_job')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_proposal_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('candidate_longlisted_for_job', 'Candidate longlisted for a job'), ('candidate_shortlisted_for_job', 'Candidate shortlisted for a job'), ('client_assigned_agency_for_job', 'Client assigns your agency to a job'), ('client_assigned_recruiter_for_job', 'Client assigns you to a job'), ('client_changed_proposal_status', 'Client changes status of a submitted candidate'), ('client_created_contract', 'Client creates a contract with your agency'), ('client_updated_job', 'Client updates a job'), ('contract_initiated_agency', 'Your contract with the client has been initiated.'), ('contract_initiated_client', 'Your contract with the agency has been initiated.'), ('contract_invitation_accepted', 'Agency accepted invitation'), ('contract_invitation_declined', 'Agency declined invitation'), ('contract_job_access_revoked_invite_ignored', 'Job access has been removed'), ('contract_job_access_revoked_no_agreement', 'Job access has been removed'), ('contract_signed_by_one_party', 'Contract is signed by one of the parties'), ('proposal_moved', 'Candidate is reallocated to a different job'), ('talent_assigned_manager_for_job', 'Talent Associate assigns you to a job')], max_length=255),
        ),
        migrations.RunPython(
            apply_new_notification_type,
            revert_apply_new_notification_type
        )
    ]
