# Generated by Django 2.2.5 on 2019-10-17 09:15

from django.db import migrations, models


def apply_required_names(apps, schema_editor):
    User = apps.get_model('core', 'User')
    Candidate = apps.get_model('core', 'Candidate')
    blank = ['', None]

    User.objects.filter(first_name__in=blank).update(first_name='Name')
    User.objects.filter(last_name__in=blank).update(last_name='Family Name')
    Candidate.objects.filter(last_name__in=blank).update(last_name='Family Name')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_proposalappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
        migrations.RunPython(
            apply_required_names, migrations.RunPython.noop
        )
    ]
