# Generated by Django 2.2.5 on 2019-10-08 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_proposal_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='suitability',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
