# Generated by Django 2.2.5 on 2019-10-22 06:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_proposal_suitability'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='page_html',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='redux_state',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
