# Generated by Django 2.2.5 on 2019-10-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_feedback_snapshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_candidate_proposed_for_job',
            new_name='email_candidate_shortlisted_for_job',
        ),
        migrations.AddField(
            model_name='user',
            name='email_candidate_longlisted_for_job',
            field=models.BooleanField(default=True),
        ),
    ]
