# Generated by Django 2.2.5 on 2019-11-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_user_frontend_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='source_details',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='source',
            field=models.CharField(
                blank=True,
                choices=[
                    ('External Agencies', 'External Agencies'),
                    ('Job Boards', 'Job Boards'),
                    ('Referrals', 'Referrals'),
                    ('Applicants (Direct)', 'Applicants (Direct)'),
                    ('Career Event', 'Career Event')
                ],
                max_length=128
            ),
        ),
    ]
