# Generated by Django 2.2.5 on 2019-11-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_proposal_remove_group_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=128)),
                ('summary', models.TextField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('currently_pursuing', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_details', to='core.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='EducationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=128)),
                ('degree', models.CharField(max_length=128)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('currently_pursuing', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_details', to='core.Candidate')),
            ],
        ),
    ]
