# Generated by Django 2.2.5 on 2019-11-28 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_educationdetail_experiencedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatenote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.Candidate'),
        ),
    ]
