# Generated by Django 2.2.5 on 2019-12-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_candidate_note_candidate_related_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetail',
            name='degree',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='educationdetail',
            name='department',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='educationdetail',
            name='institute',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='experiencedetail',
            name='company',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='experiencedetail',
            name='occupation',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='experiencedetail',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
