# Generated by Django 2.2.5 on 2019-12-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_ex_and_ed_fields_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='secondary_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
