# Generated by Django 2.2.8 on 2019-12-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_candidate_secondary_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetail',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencedetail',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
