# Generated by Django 2.2.5 on 2019-12-06 09:34

import core.models
from django.db import migrations, models
import django.db.models.deletion
import gfklookupwidget.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0122_ex_and_ed_date_start_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.get_candidate_file_path)),
                ('preview', models.FileField(upload_to=core.models.get_candidate_file_preview_path)),
                ('thumbnail', models.FileField(upload_to=core.models.get_candidate_file_thumbnail_path)),
                ('is_shared', models.BooleanField(default=False)),
                ('org_id', gfklookupwidget.fields.GfkLookupField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.Candidate')),
                ('org_content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'agency')), models.Q(('app_label', 'core'), ('model', 'client')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
