# Generated by Django 2.2.8 on 2020-01-09 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_candidatefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='original',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Candidate'),
        ),
    ]
