# Generated by Django 2.2.9 on 2020-01-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_job_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='zoho_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterUniqueTogether(name='candidate', unique_together=set(),),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(
                condition=models.Q(archived=False),
                fields=('org_content_type', 'org_id', 'zoho_id'),
                name='unique_zoho_id',
            ),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(
                condition=models.Q(archived=False),
                fields=('org_content_type', 'org_id', 'linkedin_slug'),
                name='unique_linkedin_slug',
            ),
        ),
    ]
