# Generated by Django 2.2.9 on 2020-01-27 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gfklookupwidget.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0130_expand_openings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=64)),
                (
                    'type',
                    models.CharField(
                        choices=[('candidate', 'Candidate')],
                        default='candidate',
                        max_length=16,
                    ),
                ),
                (
                    'org_id',
                    gfklookupwidget.fields.GfkLookupField(blank=True, null=True),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_tags',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'org_content_type',
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to=models.Q(
                            models.Q(('app_label', 'core'), ('model', 'agency')),
                            models.Q(('app_label', 'core'), ('model', 'client')),
                            _connector='OR',
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='contenttypes.ContentType',
                    ),
                ),
            ],
            options={'unique_together': {('org_content_type', 'org_id', 'name')},},
        ),
        migrations.CreateModel(
            name='CandidateTag',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'attached_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='attached_candidates_tags',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'candidate',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.Candidate'
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='candidate_tags',
                        to='core.Tag',
                    ),
                ),
            ],
            options={'unique_together': {('tag', 'candidate')},},
        ),
        migrations.AddField(
            model_name='candidate',
            name='tags',
            field=models.ManyToManyField(
                blank=True, through='core.CandidateTag', to='core.Tag'
            ),
        ),
    ]
