# Generated by Django 2.2.9 on 2020-02-05 13:26
from math import floor
from django.db.models.functions import Floor
from django.db import migrations, models


def round_salary_fields(apps, schema_editor):
    Candidate = apps.get_model('core', 'Candidate')
    Candidate.objects.update(salary=Floor('salary'))

    Job = apps.get_model('core', 'Job')
    Job.objects.update(salary_from=Floor('salary_from'), salary_to=Floor('salary_to'))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_primary_contact_is_required'),
    ]

    operations = [
        migrations.RunPython(round_salary_fields, migrations.RunPython.noop,),
        migrations.AlterField(
            model_name='candidate',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
