# Generated by Django 2.2.9 on 2020-02-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_salary_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='internal_status',
            field=models.CharField(
                choices=[
                    ('not_contacted', 'Not contacted'),
                    ('contacted', 'Contacted'),
                    ('generally_unqualified', 'Generally Unqualified'),
                    ('active', 'Active'),
                ],
                default='not_contacted',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_met',
            field=models.BooleanField(default=False),
        ),
    ]
