# Generated by Django 2.2.9 on 2020-01-22 12:54

from django.db import migrations, models


def revert_unique_fields(apps, schema_editor):
    Candidate = apps.get_model('core', 'Candidate')

    Candidate.objects.filter(zoho_id='').update(zoho_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_prep_unique_candidate_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(model_name='candidate', name='unique_zoho_id',),
        migrations.RemoveConstraint(
            model_name='candidate', name='unique_linkedin_slug',
        ),
        migrations.RunPython(migrations.RunPython.noop, revert_unique_fields),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='secondary_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='zoho_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('archived', False), models.Q(_negated=True, zoho_id='')
                ),
                fields=('org_content_type', 'org_id', 'zoho_id'),
                name='unique_zoho_id',
            ),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('archived', False), models.Q(_negated=True, linkedin_slug='')
                ),
                fields=('org_content_type', 'org_id', 'linkedin_slug'),
                name='unique_linkedin_slug',
            ),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('archived', False), models.Q(_negated=True, email='')
                ),
                fields=('org_content_type', 'org_id', 'email'),
                name='unique_email',
            ),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('archived', False), models.Q(_negated=True, secondary_email='')
                ),
                fields=('org_content_type', 'org_id', 'secondary_email'),
                name='unique_secondary_email',
            ),
        ),
    ]
