# Generated by Django 2.2.9 on 2020-02-17 11:45

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_additional_candidate_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.models.get_candidate_photo_file_path,
            ),
        ),
    ]
