# Generated by Django 2.2.9 on 2020-02-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_candidate_non_requried_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='internal_status',
            field=models.CharField(
                choices=[
                    ('not_contacted', 'Not contacted'),
                    ('contacted', 'Contacted'),
                    ('generally_unqualified', 'Generally unqualified'),
                    ('active', 'Active'),
                ],
                default='not_contacted',
                max_length=30,
            ),
        ),
    ]
