# Generated by Django 2.2.9 on 2020-02-28 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_internal_status_options_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='owner_agency',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='owned_clients',
                to='core.Agency',
            ),
        ),
    ]
