# Generated by Django 2.2.9 on 2020-02-28 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_proposal_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyClientInfo',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'industry',
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                'architecture_and_construction',
                                'Architecture & Construction',
                            ),
                            (
                                'automobile_or_aviation_and_aerospace',
                                'Automobile / Aviation & Aerospace',
                            ),
                            (
                                'banking_and_financial_services',
                                'Banking & Financial Services',
                            ),
                            ('consulting', 'Consulting'),
                            (
                                'education_or_training_or_coaching',
                                'Education / Training / Coaching',
                            ),
                            ('electronic_goods', 'Electronic Goods'),
                            (
                                'energy_and_natural_resources',
                                'Energy & Natural Resources',
                            ),
                            ('fintech', 'Fintech'),
                            ('food_and_beverage_or_fmcg', 'Food & Beverage / FMCG'),
                            ('hardware', 'Hardware'),
                            (
                                'healthcare_or_pharmaceutical_or_life_sciences',
                                'Healthcare / Pharmaceutical / Life Sciences',
                            ),
                            (
                                'it_or_technology_or__digital_and_telecom',
                                'IT / Technology/ Digital & Telecom',
                            ),
                            ('insurance', 'Insurance'),
                            ('legal_and_compliance', 'Legal & Compliance'),
                            (
                                'leisure_or_hospitality_or_restaurants_or_travel_and_tourism',
                                'Leisure / Hospitality / Restaurants / Travel & Tourism',
                            ),
                            (
                                'manufacturing_or_industrial',
                                'Manufacturing / Industrial',
                            ),
                            (
                                'media_or_art_and_entertaiment_or_communication_or_agency',
                                'Media / Art & Entertaiment / Communication / Agency',
                            ),
                            ('public_sector', 'Public Sector'),
                            (
                                'real_estate_or_property_and_construction',
                                'Real Estate / Property & Construction',
                            ),
                            ('recruitment', 'Recruitment'),
                            (
                                'retail_or_fashion_or_luxury_or_consumer_goods',
                                'Retail / Fashion / Luxury / Consumer Goods',
                            ),
                            ('services', 'Services'),
                            ('software', 'Software'),
                            (
                                'transportation_or_shipping_or_logistics',
                                'Transportation / Shipping / Logistics',
                            ),
                        ],
                        max_length=128,
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('key_account', 'Key account'),
                            ('auxiliary_account', 'Auxiliary account'),
                            ('new_account', 'New account'),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    'agency',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='attached_client_info',
                        to='core.Agency',
                    ),
                ),
                (
                    'client',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='attached_info',
                        to='core.Client',
                    ),
                ),
                (
                    'originator',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='discovered_clients',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={'unique_together': {('agency', 'client')},},
        ),
    ]
