# Generated by Django 2.2.9 on 2020-03-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0156_new_proposal_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='deal_final_round_sc',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='agency',
            name='deal_first_round_sc',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='agency',
            name='deal_hiring_fee_coefficient',
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name='agency',
            name='deal_intermediate_round_sc',
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name='agency',
            name='deal_offer_sc',
            field=models.FloatField(default=0.8),
        ),
    ]
