# Generated by Django 2.2.11 on 2020-03-20 10:41

import core.models
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_currencyrate'),
    ]

    operations = [
        migrations.DeleteModel(name='CurrencyRate',),
        migrations.AlterField(
            model_name='candidate',
            name='current_salary',
            field=core.models.MoneyField(
                blank=True, decimal_places=0, max_digits=19, null=True
            ),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='current_salary_currency',
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ('CAD', '$'),
                    ('HKD', '$'),
                    ('USD', '$'),
                    ('BRL', 'R$'),
                    ('GBP', '£'),
                    ('CNY', '¥'),
                    ('JPY', '¥'),
                    ('KRW', '₩'),
                    ('EUR', '€'),
                    ('INR', '₹'),
                ],
                default='JPY',
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='salary',
            field=core.models.MoneyField(
                blank=True, decimal_places=0, max_digits=19, null=True
            ),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='salary_currency',
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ('CAD', '$'),
                    ('HKD', '$'),
                    ('USD', '$'),
                    ('BRL', 'R$'),
                    ('GBP', '£'),
                    ('CNY', '¥'),
                    ('JPY', '¥'),
                    ('KRW', '₩'),
                    ('EUR', '€'),
                    ('INR', '₹'),
                ],
                default='JPY',
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name='contract',
            name='fee_currency',
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ('CAD', '$'),
                    ('HKD', '$'),
                    ('USD', '$'),
                    ('BRL', 'R$'),
                    ('GBP', '£'),
                    ('CNY', '¥'),
                    ('JPY', '¥'),
                    ('KRW', '₩'),
                    ('EUR', '€'),
                    ('INR', '₹'),
                ],
                default='JPY',
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name='contract',
            name='initial_fee',
            field=core.models.MoneyField(
                blank=True,
                currency_field_name='fee_currency',
                decimal_places=0,
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_currency',
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ('CAD', '$'),
                    ('HKD', '$'),
                    ('USD', '$'),
                    ('BRL', 'R$'),
                    ('GBP', '£'),
                    ('CNY', '¥'),
                    ('JPY', '¥'),
                    ('KRW', '₩'),
                    ('EUR', '€'),
                    ('INR', '₹'),
                ],
                default='JPY',
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_from',
            field=core.models.MoneyField(
                blank=True,
                currency_field_name='salary_currency',
                decimal_places=0,
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_to',
            field=core.models.MoneyField(
                blank=True,
                currency_field_name='salary_currency',
                decimal_places=0,
                max_digits=19,
                null=True,
            ),
        ),
    ]
