# Generated by Django 2.2.9 on 2020-03-11 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from djmoney.models.fields import CurrencyField
from core.models import MoneyField


def money_fields(name, **kwargs):
    return [
        (name, MoneyField(decimal_places=0, max_digits=19, **kwargs)),
        (
            f'{name}_currency',
            CurrencyField(
                choices=[
                    ('CAD', '$'),
                    ('HKD', '$'),
                    ('USD', '$'),
                    ('BRL', 'R$'),
                    ('GBP', '£'),
                    ('CNY', '¥'),
                    ('JPY', '¥'),
                    ('KRW', '₩'),
                    ('EUR', '€'),
                    ('INR', '₹'),
                ],
                default='JPY',
                editable=False,
                max_length=3,
            ),
        ),
    ]


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0161_candidate_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatePlacement',
            fields=[
                *money_fields('consulting_fee', null=True),
                *money_fields('offered_salary'),
                *money_fields('target_salary'),
                *money_fields('invoice_value'),
                (
                    'agency',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='candidate_placements',
                        to='core.Agency',
                    ),
                ),
                (
                    'submitted_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='submitted_candidate_placements',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('signed_at', models.DateField(auto_created=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', 'Draft'),
                            ('pending', 'Pending'),
                            ('approved', 'Approved'),
                            ('needs_revision', 'Needs revision'),
                        ],
                        default='pending',
                        max_length=14,
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='created_candidate_placements',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('starts_work_at', models.DateField()),
                ('contact_person_name', models.CharField(max_length=256)),
                ('billing_address', models.CharField(max_length=384)),
                ('should_send_invoice_email', models.BooleanField(default=False)),
                ('invoice_email', models.EmailField(max_length=254, blank=True)),
                (
                    'consulting_fee_type',
                    models.CharField(
                        choices=[('fixed', 'Fixed'), ('percentile', 'Percentile')],
                        max_length=10,
                    ),
                ),
                (
                    'consulting_fee_percentile',
                    models.DecimalField(decimal_places=4, max_digits=5, null=True),
                ),
                (
                    'contract_type',
                    models.CharField(
                        choices=[
                            ('retainer', 'Retainer'),
                            ('mts', 'MTS'),
                            ('contingent', 'Contingent'),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    'bill_description',
                    models.CharField(
                        choices=[
                            ('af', 'AF'),
                            ('slf', 'SLF'),
                            ('ff', 'FF'),
                            ('monthly', 'Monthly'),
                            ('internal', 'Internal'),
                            ('external', 'External'),
                            ('placement_fee', 'Placement Fee'),
                        ],
                        max_length=13,
                    ),
                ),
                ('invoice_issuance_date', models.DateField()),
                (
                    'ios_ioa',
                    models.CharField(
                        choices=[('ioa', 'IOA'), ('ios', 'IOS')], max_length=3
                    ),
                ),
                ('notes_to_approver', models.TextField(blank=True)),
                (
                    'industry',
                    models.CharField(
                        choices=[
                            (
                                'architecture_and_construction',
                                'Architecture & Construction',
                            ),
                            (
                                'automobile_or_aviation_and_aerospace',
                                'Automobile / Aviation & Aerospace',
                            ),
                            (
                                'banking_and_financial_services',
                                'Banking & Financial Services',
                            ),
                            ('consulting', 'Consulting'),
                            (
                                'education_or_training_or_coaching',
                                'Education / Training / Coaching',
                            ),
                            ('electronic_goods', 'Electronic Goods'),
                            (
                                'energy_and_natural_resources',
                                'Energy & Natural Resources',
                            ),
                            ('fintech', 'Fintech'),
                            ('food_and_beverage_or_fmcg', 'Food & Beverage / FMCG'),
                            ('hardware', 'Hardware'),
                            (
                                'healthcare_or_pharmaceutical_or_life_sciences',
                                'Healthcare / Pharmaceutical / Life Sciences',
                            ),
                            (
                                'it_or_technology_or__digital_and_telecom',
                                'IT / Technology/ Digital & Telecom',
                            ),
                            ('insurance', 'Insurance'),
                            ('legal_and_compliance', 'Legal & Compliance'),
                            (
                                'leisure_or_hospitality_or_restaurants_or_travel_and_tourism',
                                'Leisure / Hospitality / Restaurants / Travel & Tourism',
                            ),
                            (
                                'manufacturing_or_industrial',
                                'Manufacturing / Industrial',
                            ),
                            (
                                'media_or_art_and_entertaiment_or_communication_or_agency',
                                'Media / Art & Entertaiment / Communication / Agency',
                            ),
                            ('public_sector', 'Public Sector'),
                            (
                                'real_estate_or_property_and_construction',
                                'Real Estate / Property & Construction',
                            ),
                            ('recruitment', 'Recruitment'),
                            (
                                'retail_or_fashion_or_luxury_or_consumer_goods',
                                'Retail / Fashion / Luxury / Consumer Goods',
                            ),
                            ('services', 'Services'),
                            ('software', 'Software'),
                            (
                                'transportation_or_shipping_or_logistics',
                                'Transportation / Shipping / Logistics',
                            ),
                        ],
                        max_length=59,
                    ),
                ),
                (
                    'proposal',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='placement',
                        to='core.Proposal',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email_placement_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_placement_submitted_for_approval',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(
                choices=[
                    (
                        'agency_assigned_member_for_job',
                        'Your agency assigns you to a job',
                    ),
                    ('candidate_longlisted_for_job', 'Candidate longlisted for a job'),
                    (
                        'candidate_placement_pending',
                        'Candidate placement submitted for approval',
                    ),
                    (
                        'candidate_shortlisted_for_job',
                        'Candidate shortlisted for a job',
                    ),
                    (
                        'client_assigned_agency_for_job',
                        'Client assigns your agency to a job',
                    ),
                    (
                        'client_changed_proposal_status',
                        'Client changes status of a submitted candidate',
                    ),
                    (
                        'client_created_contract',
                        'Client creates a contract with your agency',
                    ),
                    ('client_updated_job', 'Client updates a job'),
                    (
                        'contract_initiated_agency',
                        'Your contract with the client has been initiated.',
                    ),
                    (
                        'contract_initiated_client',
                        'Your contract with the agency has been initiated.',
                    ),
                    ('contract_invitation_accepted', 'Agency accepted invitation'),
                    ('contract_invitation_declined', 'Agency declined invitation'),
                    (
                        'contract_job_access_revoked_invite_ignored',
                        'Job access has been removed',
                    ),
                    (
                        'contract_job_access_revoked_no_agreement',
                        'Job access has been removed',
                    ),
                    (
                        'contract_signed_by_one_party',
                        'Contract is signed by one of the parties',
                    ),
                    ('job_is_filled', 'Job is filled up'),
                    (
                        'proposal_appointment_confirmed',
                        'Proposal appointment confirmed',
                    ),
                    (
                        'proposal_appointment_confirmed_proposer',
                        'Proposal appointment confirmed',
                    ),
                    ('proposal_appointment_rejected', 'Proposal appointment rejected'),
                    ('proposal_moved', 'Candidate is reallocated to a different job'),
                    (
                        'talent_assigned_manager_for_job',
                        'Talent Associate assigns you to a job',
                    ),
                ],
                max_length=255,
            ),
        ),
    ]
