# Generated by Django 2.2.11 on 2020-04-01 16:35

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_candidateplacement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcategory',
            options={
                'ordering': ('title_en',),
                'verbose_name_plural': 'Job Categories (Function Focus)',
            },
        ),
        migrations.AddField(
            model_name='agencyclientinfo',
            name='account_manager',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='managed_clients',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='agencyclientinfo',
            name='billing_address',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='agencyclientinfo',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agencyclientinfo',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agencyclientinfo',
            name='portal_login',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='agencyclientinfo',
            name='portal_password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='agencyclientinfo',
            name='portal_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='agencyclientinfo',
            name='primary_contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128
            ),
        ),
        migrations.AddField(
            model_name='agencyclientinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='agencyclientinfo',
            name='updated_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='last_updated_client_info',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='client',
            name='function_focus',
            field=models.ManyToManyField(to='core.JobCategory'),
        ),
        migrations.AddField(
            model_name='client', name='website', field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='zoho_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='zoho_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='agencyclientinfo',
            name='originator',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='discovered_clients',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
