# Generated by Django 2.2.11 on 2020-03-23 12:36

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0163_client_missing_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSplitAllocation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'candidate_owner_split',
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                (
                    'lead_candidate_consultant_split',
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                (
                    'support_consultant_split',
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                (
                    'client_originator_split',
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                (
                    'lead_bd_consultant_split',
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                (
                    'candidate_source',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('External Agencies', 'External Agencies'),
                            ('Job Boards', 'Job Boards'),
                            ('Referrals', 'Referrals'),
                            ('Applicants (Direct)', 'Applicants (Direct)'),
                            ('Career Event', 'Career Event'),
                            ('BIC', 'BIC'),
                        ],
                        max_length=19,
                    ),
                ),
                (
                    'activator_split',
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                (
                    'activator',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='activator_split_allocations',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'candidate_owner',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='owner_split_allocations',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'client_originator',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='client_originator_split_allocations',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'lead_bd_consultant',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='lead_bd_consultant_split_allocations',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'lead_candidate_consultant',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='lead_candidate_consultant_split_allocations',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'placement',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='split_allocation',
                        to='core.CandidatePlacement',
                    ),
                ),
                (
                    'support_consultant',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='support_consultant_split_allocations',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'file',
                    models.FileField(
                        null=True, upload_to=core.models.get_split_allocation_file_path
                    ),
                ),
            ],
        ),
    ]
