# Generated by Django 2.2.11 on 2020-04-03 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0164_candidatesplitallocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='salary_breakdown',
            new_name='reason_for_job_changes',
        ),
        migrations.AddField(
            model_name='candidate',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='client_brief',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='client_expertise',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='companies_already_applied_to',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='companies_applied_to',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='department',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='industry',
            field=models.CharField(
                blank=True,
                choices=[
                    ('architecture_and_construction', 'Architecture & Construction'),
                    (
                        'automobile_or_aviation_and_aerospace',
                        'Automobile / Aviation & Aerospace',
                    ),
                    ('banking_and_financial_services', 'Banking & Financial Services'),
                    ('consulting', 'Consulting'),
                    (
                        'education_or_training_or_coaching',
                        'Education / Training / Coaching',
                    ),
                    ('electronic_goods', 'Electronic Goods'),
                    ('energy_and_natural_resources', 'Energy & Natural Resources'),
                    ('fintech', 'Fintech'),
                    ('food_and_beverage_or_fmcg', 'Food & Beverage / FMCG'),
                    ('hardware', 'Hardware'),
                    (
                        'healthcare_or_pharmaceutical_or_life_sciences',
                        'Healthcare / Pharmaceutical / Life Sciences',
                    ),
                    (
                        'it_or_technology_or__digital_and_telecom',
                        'IT / Technology/ Digital & Telecom',
                    ),
                    ('insurance', 'Insurance'),
                    ('legal_and_compliance', 'Legal & Compliance'),
                    (
                        'leisure_or_hospitality_or_restaurants_or_travel_and_tourism',
                        'Leisure / Hospitality / Restaurants / Travel & Tourism',
                    ),
                    ('manufacturing_or_industrial', 'Manufacturing / Industrial'),
                    (
                        'media_or_art_and_entertaiment_or_communication_or_agency',
                        'Media / Art & Entertaiment / Communication / Agency',
                    ),
                    ('public_sector', 'Public Sector'),
                    (
                        'real_estate_or_property_and_construction',
                        'Real Estate / Property & Construction',
                    ),
                    ('recruitment', 'Recruitment'),
                    (
                        'retail_or_fashion_or_luxury_or_consumer_goods',
                        'Retail / Fashion / Luxury / Consumer Goods',
                    ),
                    ('services', 'Services'),
                    ('software', 'Software'),
                    (
                        'transportation_or_shipping_or_logistics',
                        'Transportation / Shipping / Logistics',
                    ),
                ],
                max_length=59,
            ),
        ),
        migrations.AddField(
            model_name='candidate',
            name='nationality',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='candidate',
            name='pull_factors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='push_factors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='referred_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='referred_candidates',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='candidate',
            name='work_direct',
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128
            ),
        ),
        migrations.AddField(
            model_name='candidate',
            name='work_mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128
            ),
        ),
    ]
