# Generated by Django 2.2.11 on 2020-04-03 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0165_candidate_missing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='primary_contact',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='primary_jobs',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='job',
            name='skill_domain',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='jobs',
                to='core.SkillDomain',
            ),
        ),
        migrations.AddField(
            model_name='job',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencyclientinfo',
            name='tier_one_companies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agencyclientinfo',
            name='tier_two_companies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='work_experience',
            field=models.CharField(
                blank=True,
                choices=[
                    ('none', 'None'),
                    ('fresher', 'Fresher'),
                    ('zero_one_year', '0-1 year'),
                    ('one_three_years', '1-3 years'),
                    ('four_five_years', '4-5 years'),
                    ('five_more_years', '5+ years'),
                ],
                default='none',
                max_length=16,
            ),
        ),
    ]
