# Generated by Django 2.2.11 on 2020-04-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0167_users_zoho_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencyclientinfo', name='tier_one_companies',
        ),
        migrations.RemoveField(
            model_name='agencyclientinfo', name='tier_two_companies',
        ),
        migrations.AddField(
            model_name='job',
            name='tier_one_companies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='tier_two_companies',
            field=models.TextField(blank=True),
        ),
    ]
