# Generated by Django 2.2.11 on 2020-04-02 06:58

from django.db import migrations, models
from django.utils.timezone import now


def set_created_at(apps, schema_editor):
    CandidatePlacement = apps.get_model('core', 'candidateplacement')

    CandidatePlacement.objects.filter(created_at__isnull=True).update(created_at=now())


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0168_job_tier_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateplacement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RunPython(set_created_at, migrations.RunPython.noop,),
        migrations.AlterField(
            model_name='candidateplacement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(model_name='user', name='email_placement_approved',),
        migrations.AddField(
            model_name='user',
            name='email_placement_sent_to_revision',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(
                choices=[
                    (
                        'agency_assigned_member_for_job',
                        'Your agency assigns you to a job',
                    ),
                    ('candidate_longlisted_for_job', 'Candidate longlisted for a job'),
                    (
                        'candidate_placement_approved',
                        'Candidate placement sent to revision',
                    ),
                    (
                        'candidate_placement_needs_revision',
                        'Candidate placement sent to revision',
                    ),
                    (
                        'candidate_placement_pending',
                        'Candidate placement submitted for approval',
                    ),
                    (
                        'candidate_placement_pending_reminder',
                        'Candidate placement sent to revision',
                    ),
                    (
                        'candidate_shortlisted_for_job',
                        'Candidate shortlisted for a job',
                    ),
                    (
                        'client_assigned_agency_for_job',
                        'Client assigns your agency to a job',
                    ),
                    (
                        'client_changed_proposal_status',
                        'Client changes status of a submitted candidate',
                    ),
                    (
                        'client_created_contract',
                        'Client creates a contract with your agency',
                    ),
                    ('client_updated_job', 'Client updates a job'),
                    (
                        'contract_initiated_agency',
                        'Your contract with the client has been initiated.',
                    ),
                    (
                        'contract_initiated_client',
                        'Your contract with the agency has been initiated.',
                    ),
                    ('contract_invitation_accepted', 'Agency accepted invitation'),
                    ('contract_invitation_declined', 'Agency declined invitation'),
                    (
                        'contract_job_access_revoked_invite_ignored',
                        'Job access has been removed',
                    ),
                    (
                        'contract_job_access_revoked_no_agreement',
                        'Job access has been removed',
                    ),
                    (
                        'contract_signed_by_one_party',
                        'Contract is signed by one of the parties',
                    ),
                    ('job_is_filled', 'Job is filled up'),
                    (
                        'proposal_appointment_confirmed',
                        'Proposal appointment confirmed',
                    ),
                    (
                        'proposal_appointment_confirmed_proposer',
                        'Proposal appointment confirmed',
                    ),
                    ('proposal_appointment_rejected', 'Proposal appointment rejected'),
                    ('proposal_moved', 'Candidate is reallocated to a different job'),
                    (
                        'talent_assigned_manager_for_job',
                        'Talent Associate assigns you to a job',
                    ),
                ],
                max_length=255,
            ),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email_placement_sent_to_revision',
            new_name='email_candidate_placement_needs_revision',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email_placement_submitted_for_approval',
            new_name='email_candidate_placement_pending',
        ),
        migrations.AddField(
            model_name='user',
            name='email_candidate_placement_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='notify_if_candidate_placement_approved',
            field=models.BooleanField(
                default=False,
                verbose_name='Notify members if candidate placement is approved',
            ),
        ),
    ]
