# Generated by Django 2.2.11 on 2020-04-10 14:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0169_candidateplacement_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='zoho_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='zoho_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='skilldomain',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
