# Generated by Django 2.2.11 on 2020-04-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0174_agencyclientinfo_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateplacement',
            name='approved_at',
            field=models.DateField(null=True),
        ),
    ]
