# Generated by Django 2.2.11 on 2020-04-27 15:02

from django.db import migrations, models
from djmoney.models.fields import CurrencyField
from core.models import MoneyField


def generate_invoice_number(last_order, date):
    return '{order}{date:%Y%m}'.format(order=last_order + 1, date=date)


def set_defaults(apps, schema_editor):
    Placement = apps.get_model('core', 'CandidatePlacement')

    i = 1
    for placement in Placement.objects.all():
        if placement.status == 'approved':
            placement.invoice_number = generate_invoice_number(
                i, placement.invoice_issuance_date
            )
        placement.consumption_tax = 0.1 * placement.invoice_value
        placement.save()
        i += 1


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0175_candidateplacement_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateplacement',
            name='invoice_due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='candidateplacement',
            name='invoice_number',
            field=models.CharField(null=True, max_length=15),
        ),
        migrations.AddField(
            model_name='candidateplacement',
            name='invoice_paid_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='candidateplacement',
            name='invoice_status',
            field=models.CharField(
                choices=[
                    ('paid', 'Paid'),
                    ('overdue', 'Overdue'),
                    ('sent', 'Sent'),
                    ('not_sent', 'Not Sent'),
                    ('cancelled', 'Cancelled'),
                    ('backed_out', 'Backed Out'),
                ],
                default='not_sent',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='candidateplacement',
            name='consumption_tax',
            field=MoneyField(decimal_places=0, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='candidateplacement',
            name='consumption_tax_currency',
            field=CurrencyField(
                choices=[
                    ('CAD', '$'),
                    ('HKD', '$'),
                    ('USD', '$'),
                    ('BRL', 'R$'),
                    ('GBP', '£'),
                    ('CNY', '¥'),
                    ('JPY', '¥'),
                    ('KRW', '₩'),
                    ('EUR', '€'),
                    ('INR', '₹'),
                ],
                default='JPY',
                editable=False,
                max_length=3,
            ),
        ),
        migrations.RunPython(set_defaults, migrations.RunPython.noop,),
    ]
