# Generated by Django 2.2.11 on 2020-04-28 08:38

from django.db import migrations

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0176_placement_invoice_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateplacement',
            name='consumption_tax',
            field=core.models.MoneyField(decimal_places=0, max_digits=19),
        ),
    ]
