# Generated by Django 2.2.11 on 2020-05-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0181_create_placements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee', name='nbv_date', field=models.DateField(),
        ),
        migrations.RemoveField(model_name='fee', name='ios_ioa'),
        migrations.RemoveField(model_name='fee', name='offered_salary',),
        migrations.RemoveField(model_name='fee', name='offered_salary_currency'),
        migrations.RemoveField(model_name='fee', name='target_salary',),
        migrations.RemoveField(model_name='fee', name='target_salary_currency'),
        migrations.RemoveField(
            model_name='feesplitallocation', name='candidate_source',
        ),
        migrations.RemoveField(model_name='fee', name='contact_person_name',),
        migrations.RemoveField(model_name='fee', name='contract_type',),
        migrations.RemoveField(model_name='fee', name='industry',),
        migrations.AlterField(
            model_name='fee',
            name='job_contract',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                to='core.JobAgencyContract',
                related_name='fees',
            ),
        ),
    ]
