# Generated by Django 2.2.11 on 2020-06-18 11:50

from django.db import migrations, models
from django.db.models import F
from django.db.models.deletion import CASCADE
from django.conf import settings


def set_listed_at(apps, schema_editor):
    Proposal = apps.get_model('core', 'Proposal')
    Proposal.objects.filter(stage='shortlist').update(shortlisted_by=F('created_by'),)
    Proposal.objects.filter(stage='longlist').update(longlisted_by=F('created_by'),)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0185_rich_text_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='longlisted_by',
            field=models.ForeignKey(
                null=True,
                on_delete=CASCADE,
                related_name='longlisted_proposals',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='proposal',
            name='shortlisted_by',
            field=models.ForeignKey(
                null=True,
                on_delete=CASCADE,
                related_name='shortlisted_proposals',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(set_listed_at, migrations.RunPython.noop),
    ]
