# Generated by Django 2.2.13 on 2020-07-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0189_creator_timezone_updated_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
