# Generated by Django 2.2.15 on 2020-09-11 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0190_fee_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(
                choices=[
                    (
                        'agency_assigned_member_for_job',
                        'Your agency assigns you to a job',
                    ),
                    ('candidate_longlisted_for_job', 'Candidate longlisted for a job'),
                    (
                        'candidate_shortlisted_for_job',
                        'Candidate shortlisted for a job',
                    ),
                    (
                        'client_assigned_agency_for_job',
                        'Client assigns your agency to a job',
                    ),
                    (
                        'client_changed_proposal_status',
                        'Client changes status of a submitted candidate',
                    ),
                    (
                        'client_created_contract',
                        'Client creates a contract with your agency',
                    ),
                    ('client_updated_job', 'Client updates a job'),
                    (
                        'contract_initiated_agency',
                        'Your contract with the client has been initiated.',
                    ),
                    (
                        'contract_initiated_client',
                        'Your contract with the agency has been initiated.',
                    ),
                    ('contract_invitation_accepted', 'Agency accepted invitation'),
                    ('contract_invitation_declined', 'Agency declined invitation'),
                    (
                        'contract_job_access_revoked_invite_ignored',
                        'Job access has been removed',
                    ),
                    (
                        'contract_job_access_revoked_no_agreement',
                        'Job access has been removed',
                    ),
                    (
                        'contract_signed_by_one_party',
                        'Contract is signed by one of the parties',
                    ),
                    ('fee_approved', 'Fee is approved'),
                    ('fee_draft', 'Fee is set as draft'),
                    ('fee_needs_revision', 'Fee is sent to revision'),
                    ('fee_pending', 'Fee is submitted for approval'),
                    ('fee_pending_reminder', 'Fee is waiting approval'),
                    ('job_is_filled', 'Job is filled up'),
                    ('placement_fee_approved', 'Candidate placement is approved'),
                    ('placement_fee_draft', 'Candidate placement is set as draft'),
                    (
                        'placement_fee_needs_revision',
                        'Candidate placement is sent to revision',
                    ),
                    (
                        'placement_fee_pending',
                        'Candidate placement is submitted for approval',
                    ),
                    (
                        'placement_fee_pending_reminder',
                        'Candidate placement is sent to revision',
                    ),
                    (
                        'proposal_appointment_confirmed',
                        'Proposal appointment confirmed',
                    ),
                    (
                        'proposal_appointment_confirmed_proposer',
                        'Proposal appointment confirmed',
                    ),
                    ('proposal_appointment_rejected', 'Proposal appointment rejected'),
                    ('proposal_moved', 'Candidate is reallocated to a different job'),
                    (
                        'talent_assigned_manager_for_job',
                        'Talent Associate assigns you to a job',
                    ),
                    ('user_mentioned_in_comment', 'User is mentioned'),
                ],
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name='CandidateComment',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('text', models.TextField()),
                ('public', models.BooleanField(default=False)),
                ('system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'author',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'candidate',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.Candidate'
                    ),
                ),
            ],
        ),
    ]
