# Generated by Django 2.2.16 on 2020-11-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0192_candidate_comment_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(
                choices=[
                    (
                        'agency_assigned_member_for_job',
                        'Your agency assigns you to a job',
                    ),
                    ('candidate_longlisted_for_job', 'Candidate longlisted for a job'),
                    (
                        'candidate_shortlisted_for_job',
                        'Candidate shortlisted for a job',
                    ),
                    (
                        'client_assigned_agency_for_job',
                        'Client assigns your agency to a job',
                    ),
                    (
                        'client_changed_proposal_status',
                        'Client changes status of a submitted candidate',
                    ),
                    (
                        'client_created_contract',
                        'Client creates a contract with your agency',
                    ),
                    ('client_updated_job', 'Client updates a job'),
                    (
                        'contract_initiated_agency',
                        'Your contract with the client has been initiated.',
                    ),
                    (
                        'contract_initiated_client',
                        'Your contract with the agency has been initiated.',
                    ),
                    ('contract_invitation_accepted', 'Agency accepted invitation'),
                    ('contract_invitation_declined', 'Agency declined invitation'),
                    (
                        'contract_job_access_revoked_invite_ignored',
                        'Job access has been removed',
                    ),
                    (
                        'contract_job_access_revoked_no_agreement',
                        'Job access has been removed',
                    ),
                    (
                        'contract_signed_by_one_party',
                        'Contract is signed by one of the parties',
                    ),
                    ('fee_approved', 'Fee is approved'),
                    ('fee_draft', 'Fee is set as draft'),
                    ('fee_needs_revision', 'Fee is sent to revision'),
                    ('fee_pending', 'Fee is submitted for approval'),
                    ('fee_pending_reminder', 'Fee is waiting approval'),
                    ('job_is_filled', 'Job is filled up'),
                    ('placement_fee_approved', 'Candidate placement is approved'),
                    ('placement_fee_draft', 'Candidate placement is set as draft'),
                    (
                        'placement_fee_needs_revision',
                        'Candidate placement is sent to revision',
                    ),
                    (
                        'placement_fee_pending',
                        'Candidate placement is submitted for approval',
                    ),
                    (
                        'placement_fee_pending_reminder',
                        'Candidate placement is sent to revision',
                    ),
                    (
                        'proposal_appointment_confirmed',
                        'Proposal appointment confirmed',
                    ),
                    (
                        'proposal_appointment_confirmed_proposer',
                        'Proposal appointment confirmed',
                    ),
                    ('proposal_appointment_rejected', 'Proposal appointment rejected'),
                    ('proposal_moved', 'Candidate is reallocated to a different job'),
                    (
                        'proposal_public_application_confirmed',
                        'Proposal new public application',
                    ),
                    (
                        'talent_assigned_manager_for_job',
                        'Talent Associate assigns you to a job',
                    ),
                    ('user_mentioned_in_comment', 'User is mentioned'),
                    (
                        'user_mentioned_in_comment_deleted',
                        'Comment mentioning user is deleted',
                    ),
                ],
                max_length=255,
            ),
        ),
    ]
