# Generated by Django 2.2.16 on 2020-11-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0193_public_app_notification_verb'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='is_direct_application',
            field=models.BooleanField(default=False),
        ),
    ]
