# Generated by Django 2.2.16 on 2020-11-10 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0194_proposal_is_direct_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='candidate_requirements',
            new_name='requirements',
        ),
        migrations.RenameField(
            model_name='job', old_name='description', new_name='responsibilities',
        ),
        migrations.RenameField(
            model_name='job', old_name='target_date', new_name='target_hiring_date',
        ),
        migrations.RenameField(
            model_name='job', old_name='city', new_name='work_location',
        ),
        migrations.RenameField(
            model_name='job', old_name='primary_contact', new_name='recruiter',
        ),
    ]
