# Generated by Django 2.2.17 on 2020-11-11 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0195_update_jobs_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='additional_leaves',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job', name='bonus_system', field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='break_time_mins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='commutation_allowance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='job',
            name='educational_level',
            field=models.CharField(
                blank=True,
                choices=[
                    ('none', 'None'),
                    ('highschool', 'High School Diploma'),
                    ('bachelors', "Bachelor's Degree"),
                    ('masters', "Master's Degree"),
                    ('phd', 'PhD'),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name='job',
            name='flexitime_eligibility',
            field=models.CharField(
                blank=True,
                choices=[('eligible', 'Eligible'), ('not_eligible', 'Not Eligible')],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name='job', name='hiring_process', field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='interviews_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job', name='mission', field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='other_benefits',
            field=models.CharField(
                blank=True,
                choices=[
                    ('visa', 'Visa Sponsorship'),
                    ('relocation', 'Relocation Assistance'),
                    ('wellness', 'Gym / Wellness Membership'),
                    ('coffee', 'Free Coffee'),
                ],
                max_length=31,
            ),
        ),
        migrations.AddField(
            model_name='job',
            name='overtime_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job', name='paid_leaves', field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='probation_period_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='reason_for_opening',
            field=models.CharField(
                blank=True,
                choices=[('replacement', 'Replacement'), ('new', 'New')],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name='job',
            name='social_insurances',
            field=models.CharField(
                blank=True,
                choices=[
                    ('health', 'Health Insurance'),
                    ('employment', 'Employment Insurance'),
                    ('welfare_pension', 'Welfare Pension Insurance'),
                    (
                        'accident_compensation',
                        'Workers Accident Compensation Insurance',
                    ),
                ],
                max_length=55,
            ),
        ),
        migrations.AddField(
            model_name='job', name='working_hours', field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='HiringCriterion',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=128)),
                (
                    'job',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='hiring_criteria',
                        to='core.Job',
                    ),
                ),
            ],
        ),
    ]
