# Generated by Django 2.2.17 on 2020-11-16 03:33

from django.db import migrations


DATA = [
    'Accounting',
    'Administrative & Office Support',
    'Arts and Design',
    'Consulting',
    'Finance',
    'Human Resources',
    'Information Technology',
    'Legal & Compliance',
    'Marketing',
    'Media & Communications',
    'Sales',
    'Supply Chain Management',
    'Academia & Public Sector',
    'Life Sciences',
    'Physical Sciences',
    'Industrial & Manufacturing',
    'Real Estate',
    'General Management',
]


def add_default_functions(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Function = apps.get_model('core', 'Function')
    Function.objects.all().delete()
    for title in sorted(DATA):
        Function.objects.using(db_alias).update_or_create(title_en=title.strip())


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0196_jobs_new_fields'),
    ]

    operations = [
        migrations.RenameModel(old_name='JobCategory', new_name='Function',),
        migrations.AlterModelOptions(
            name='function', options={'ordering': ('title_en',)},
        ),
        migrations.RenameField(
            model_name='job', old_name='category', new_name='function',
        ),
        migrations.RunPython(add_default_functions, migrations.RunPython.noop),
    ]
