# Generated by Django 2.2.17 on 2020-11-16 08:00

from django.db import migrations, models


def fulltime_to_employment_type(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Job = apps.get_model('core', 'Job')
    for job in Job.objects.all():
        if job.fulltime:
            job.employment_type = 'permanent'
        else:
            job.employment_type = 'parttime'
        job.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0197_jobs_category_to_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('permanent', 'Permanent Employee'),
                    ('parttime', 'Part Time Employee'),
                    ('fixedterm', 'Fixed Term Contract Employee'),
                    ('dispatch', 'Dispatch'),
                    ('freelance', 'Freelance'),
                ],
                max_length=9,
            ),
        ),
        migrations.RunPython(fulltime_to_employment_type, migrations.RunPython.noop),
    ]
