# Generated by Django 2.2.17 on 2020-11-17 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0198_jobs_employment_type'),
    ]

    operations = [
        migrations.RemoveField(model_name='job', name='fulltime',),
    ]
