# Generated by Django 2.2.17 on 2020-11-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0199_jobs_remove_fulltime'),
    ]

    operations = [
        migrations.RemoveField(model_name='job', name='remote',),
        migrations.AddField(
            model_name='job',
            name='telework_eligibility',
            field=models.CharField(
                choices=[
                    ('onsite', 'On Site Only'),
                    ('possible', 'Remote Possible'),
                    ('remote', 'Remote Only'),
                ],
                default='onsite',
                max_length=8,
            ),
        ),
    ]
