# Generated by Django 2.2.17 on 2020-11-18 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0200_job_remote_to_telework_eligibility'),
    ]

    operations = [
        migrations.RemoveField(model_name='job', name='critical_factors',),
        migrations.RemoveField(model_name='job', name='skill_domain',),
    ]
