# Generated by Django 2.2.17 on 2020-11-19 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0201_jobs_remove_critical_factors_skill_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(
                choices=[('candidate', 'Candidate'), ('skill', 'Skill')],
                default='candidate',
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'attached_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='attached_job_skills',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'job',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.Job'
                    ),
                ),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='job_skills',
                        to='core.Tag',
                    ),
                ),
            ],
            options={'unique_together': {('job', 'tag')},},
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(
                blank=True, through='core.JobSkill', to='core.Tag'
            ),
        ),
    ]
