# Generated by Django 2.2.17 on 2020-11-27 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0202_jobs_add_skills'),
    ]

    operations = [
        migrations.RemoveField(model_name='job', name='interviews_count',),
    ]
