# Generated by Django 2.2.17 on 2020-12-12 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0203_remove_job_interviews_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentTemplate',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'appointment_type',
                    models.CharField(
                        choices=[
                            ('assignment', 'Assignment'),
                            ('technical_fit', 'Technical Fit'),
                            ('cultural_fit', 'Cultural Fit'),
                            ('general', 'General'),
                            ('cross_team', 'Cross-team'),
                        ],
                        default='general',
                        max_length=15,
                    ),
                ),
                ('default', models.BooleanField(default=False)),
                ('default_order', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobAppointmentTemplate',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'appointment_type',
                    models.CharField(
                        choices=[
                            ('assignment', 'Assignment'),
                            ('technical_fit', 'Technical Fit'),
                            ('cultural_fit', 'Cultural Fit'),
                            ('general', 'General'),
                            ('cross_team', 'Cross-team'),
                        ],
                        default='general',
                        max_length=15,
                    ),
                ),
                ('default', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=1024)),
            ],
        ),
        migrations.RemoveConstraint(model_name='proposal', name='stage_data_exists',),
        migrations.RemoveField(model_name='proposal', name='longlisted_by',),
        migrations.RemoveField(model_name='proposal', name='shortlisted_by',),
        migrations.RemoveField(model_name='proposal', name='stage',),
        migrations.AddField(
            model_name='proposal',
            name='status_last_updated_by',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='status_last_updated_proposals',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='proposalappointment',
            name='appointment_type',
            field=models.CharField(
                choices=[
                    ('assignment', 'Assignment'),
                    ('technical_fit', 'Technical Fit'),
                    ('cultural_fit', 'Cultural Fit'),
                    ('general', 'General'),
                    ('cross_team', 'Cross-team'),
                ],
                default='general',
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name='proposalstatus',
            name='stage',
            field=models.CharField(
                choices=[
                    ('associated', 'Associated'),
                    ('pre_screening', 'Pre-Screening'),
                    ('submissions', 'Submissions'),
                    ('screening', 'Screening'),
                    ('first_interview', 'First Interview'),
                    ('interviewing', 'Interviewing'),
                    ('final_interview', 'Final Interview'),
                    ('offering', 'Offering'),
                    ('hired', 'Hired'),
                ],
                default='associated',
                max_length=32,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposalstatus',
            name='group',
            field=models.CharField(
                choices=[
                    ('associated_candidate_to_job', 'Associated Candidate to Job'),
                    ('interested_and_suitable', 'Interested and Suitable'),
                    ('not_interested_and_suitable', 'Not interested and Suitable'),
                    ('not_interested_and_unsuitable', 'Not interested and Unsuitable'),
                    ('contacted', 'Contacted'),
                    ('met_unsuitable', 'Met - Unsuitable'),
                    ('met_suitable', 'Met - Suitable'),
                    ('applied_by_candidate', 'Applied by Candidate'),
                    ('submitted_by_agent', 'Submitted by Agent'),
                    (
                        'submitted_by_internal_recruiter',
                        'Submitted by Internal Recruiter',
                    ),
                    ('submitted_by_referral', 'Submitted by Referral'),
                    ('submitted_to_client', 'Submitted to Client'),
                    ('submitted_to_hiring_manager', 'Submitted to Hiring Manager'),
                    ('rejected_by_client', 'Rejected // Rejected by Client'),
                    ('on_hold_by_client', 'On Hold // On Hold by Client'),
                    ('suitable_approved_by_client', 'Suitable // Approved by Client'),
                    ('rejected_by_agent', 'Rejected by Agent'),
                    ('confirmed_client_availability', 'Confirmed Client Availability'),
                    (
                        'confirmed_candidate_availability',
                        'Confirmed Candidate Availability',
                    ),
                    ('scheduled_interview', 'Scheduled Interview'),
                    (
                        'completed_interview_waiting_for_feedback',
                        'Completed Interview (waiting for feedback)',
                    ),
                    (
                        'passed_interview_proceed_to_next_stage',
                        'Passed Interview (proceed to next stage)',
                    ),
                    ('rejected_by_candidate', 'Rejected by Candidate'),
                    ('decided_to_offer', 'Decided to Offer'),
                    ('prepared_the_offer', 'Prepared the Offer'),
                    ('presented_the_offer', 'Presented the Offer'),
                    ('offer_accepted', 'Offer Accepted'),
                    ('offer_declined', 'Offer Declined'),
                    ('offer_withdrawn', 'Offer Withdrawn'),
                    ('pending_start_date', 'Pending Start Date'),
                    ('started', 'Started'),
                    ('no_show', 'No Show'),
                    ('probation_passed', 'Probation Passed'),
                    ('probation_not_passed', 'Probation Not Passed'),
                    (
                        'terminated_during_warranty_period',
                        'Terminated During Warranty Period',
                    ),
                    (
                        'terminated_during_probation_period',
                        'Terminated During Probation Period',
                    ),
                    (
                        'resigned_during_warranty_period',
                        'Resigned During Warranty Period',
                    ),
                    (
                        'resigned_during_probation_period',
                        'Resigned During Probation Period',
                    ),
                ],
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name='jobappointmenttemplate',
            name='job',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='appointment_templates',
                to='core.Job',
            ),
        ),
    ]
