# Generated by Django 2.2.17 on 2020-12-08 05:02

from django.db import migrations


# Note(ZOO-722): default appointment templates
APPOINTMENT_TEMPLATES = [
    {'appointment_type': 'general', 'default_order': 10},
    {'appointment_type': 'technical fit', 'default_order': 20},
    {'appointment_type': 'cultural fit', 'default_order': 30},
]


def add_appointment_templates(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    AppointmentTemplate = apps.get_model('core', 'AppointmentTemplate')
    for item in APPOINTMENT_TEMPLATES:
        appointment_template = AppointmentTemplate.objects.using(db_alias).create(
            default=True, **item
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0205_new_default_proposal_status'),
    ]

    operations = [
        migrations.RunPython(add_appointment_templates, migrations.RunPython.noop)
    ]
