# Generated by Django 2.2.17 on 2020-12-28 14:45

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0208_candidate_other_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='bonus_and_commissions',
            field=core.models.MoneyField(
                blank=True,
                currency_field_name='current_salary_currency',
                decimal_places=0,
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='candidate',
            name='other_allowances',
            field=core.models.MoneyField(
                blank=True,
                currency_field_name='current_salary_currency',
                decimal_places=0,
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='candidate',
            name='rsu_and_options',
            field=core.models.MoneyField(
                blank=True,
                currency_field_name='current_salary_currency',
                decimal_places=0,
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='current_salary',
            field=core.models.MoneyField(
                blank=True,
                currency_field_name='current_salary_currency',
                decimal_places=0,
                max_digits=19,
                null=True,
            ),
        ),
    ]
