# Generated by Django 2.2.17 on 2021-01-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0209_add_salary_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.IntegerField(
                choices=[
                    (0, 'Survival'),
                    (1, 'Daily Conversation'),
                    (2, 'Advanced'),
                    (3, 'Fluent'),
                    (4, 'Native'),
                ]
            ),
        ),
    ]
