# Generated by Django 2.2.17 on 2021-01-06 05:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0210_update_language_level_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cv_ja',
            field=models.FileField(
                blank=True,
                help_text='Shokumu-keirekisho',
                null=True,
                upload_to=core.models.get_cv_ja_upload_to,
            ),
        ),
        migrations.AddField(
            model_name='candidate',
            name='cv_ja_thumbnail',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=core.models.get_cv_ja_thumbnail_upload_to,
            ),
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume_ja',
            field=models.FileField(
                blank=True,
                help_text='Rirekisho',
                null=True,
                upload_to=core.models.get_resume_ja_upload_to,
            ),
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume_ja_thumbnail',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=core.models.get_resume_ja_thumbnail_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(
                blank=True,
                help_text='English Resume',
                null=True,
                upload_to=core.models.get_resume_upload_to,
            ),
        ),
    ]
