# Generated by Django 2.2.17 on 2021-01-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0211_add_new_resume_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
