# Generated by Django 2.2.17 on 2021-01-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0213_update_proposal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalstatus',
            name='group',
            field=models.CharField(
                choices=[
                    ('associated_candidate_to_job', 'Associated Candidate to Job'),
                    ('interested_and_suitable', 'Interested and Suitable'),
                    ('not_interested_and_suitable', 'Not interested and Suitable'),
                    ('contacted', 'Contacted'),
                    ('met_suitable', 'Met - Suitable'),
                    ('applied_by_candidate', 'Applied by Candidate'),
                    ('submitted_by_agent', 'Submitted by Agent'),
                    (
                        'submitted_by_internal_recruiter',
                        'Submitted by Internal Recruiter',
                    ),
                    ('submitted_by_referral', 'Submitted by Referral'),
                    ('submitted_to_client', 'Submitted to Client'),
                    ('submitted_to_hiring_manager', 'Submitted to Hiring Manager'),
                    ('on_hold_by_client', 'On Hold // On Hold by Client'),
                    ('suitable_approved_by_client', 'Suitable // Approved by Client'),
                    ('confirmed_client_availability', 'Confirmed Client Availability'),
                    (
                        'confirmed_candidate_availability',
                        'Confirmed Candidate Availability',
                    ),
                    ('scheduled_interview', 'Scheduled Interview'),
                    (
                        'completed_interview_waiting_for_feedback',
                        'Completed Interview (waiting for feedback)',
                    ),
                    (
                        'passed_interview_proceed_to_next_stage',
                        'Passed Interview (proceed to next stage)',
                    ),
                    ('decided_to_offer', 'Decided to Offer'),
                    ('prepared_the_offer', 'Prepared the Offer'),
                    ('presented_the_offer', 'Presented the Offer'),
                    ('offer_accepted', 'Offer Accepted'),
                    ('pending_start_date', 'Pending Start Date'),
                    ('started', 'Started'),
                    ('no_show', 'No Show'),
                    ('probation_passed', 'Probation Passed'),
                    ('probation_not_passed', 'Probation Not Passed'),
                    (
                        'terminated_during_warranty_period',
                        'Terminated During Warranty Period',
                    ),
                    (
                        'terminated_during_probation_period',
                        'Terminated During Probation Period',
                    ),
                    (
                        'resigned_during_warranty_period',
                        'Resigned During Warranty Period',
                    ),
                    (
                        'resigned_during_probation_period',
                        'Resigned During Probation Period',
                    ),
                ],
                max_length=64,
            ),
        ),
    ]
