# Generated by Django 2.2.17 on 2021-01-20 05:15

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0214_update_proposal_status_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='fee_currency',
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ('USD', '$'),
                    ('CAD', 'C$'),
                    ('HKD', 'HK$'),
                    ('BRL', 'R$'),
                    ('GBP', '£'),
                    ('CNY', '¥'),
                    ('JPY', '¥'),
                    ('KRW', '₩'),
                    ('EUR', '€'),
                    ('INR', '₹'),
                ],
                default='JPY',
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_currency',
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ('USD', '$'),
                    ('CAD', 'C$'),
                    ('HKD', 'HK$'),
                    ('BRL', 'R$'),
                    ('GBP', '£'),
                    ('CNY', '¥'),
                    ('JPY', '¥'),
                    ('KRW', '₩'),
                    ('EUR', '€'),
                    ('INR', '₹'),
                ],
                default='JPY',
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name='placement',
            name='current_salary_currency',
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ('USD', '$'),
                    ('CAD', 'C$'),
                    ('HKD', 'HK$'),
                    ('BRL', 'R$'),
                    ('GBP', '£'),
                    ('CNY', '¥'),
                    ('JPY', '¥'),
                    ('KRW', '₩'),
                    ('EUR', '€'),
                    ('INR', '₹'),
                ],
                default='JPY',
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name='placement',
            name='offered_salary_currency',
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ('USD', '$'),
                    ('CAD', 'C$'),
                    ('HKD', 'HK$'),
                    ('BRL', 'R$'),
                    ('GBP', '£'),
                    ('CNY', '¥'),
                    ('JPY', '¥'),
                    ('KRW', '₩'),
                    ('EUR', '€'),
                    ('INR', '₹'),
                ],
                default='JPY',
                editable=False,
                max_length=3,
            ),
        ),
    ]
