# Generated by Django 2.2.17 on 2021-01-27 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0217_default_proposal_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalQuickAction',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'action',
                    models.CharField(
                        choices=[
                            ('reject', 'Reject'),
                            ('change_status', 'Change Status'),
                            ('passed_interview', 'Passed Interview'),
                            ('schedule_interview', 'Schedule Interview'),
                            ('end_interview', 'End of Interview'),
                        ],
                        max_length=18,
                    ),
                ),
                ('org_type', models.CharField(max_length=8)),
                ('label', models.CharField(blank=True, max_length=32)),
                ('label_en', models.CharField(blank=True, max_length=32, null=True)),
                ('label_ja', models.CharField(blank=True, max_length=32, null=True)),
                (
                    'proposal_status',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='quick_actions',
                        to='core.ProposalStatus',
                    ),
                ),
                (
                    'to_proposal_status',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='core.ProposalStatus',
                    ),
                ),
            ],
        ),
    ]
