# Generated by Django 2.2.17 on 2021-01-29 07:25

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0219_default_quick_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_postal_code',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_prefecture',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_street',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='candidate',
            name='expectations_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.CharField(
                choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')],
                default='other',
                max_length=6,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_change_urgency',
            field=models.CharField(
                blank=True,
                choices=[
                    ('urgent', 'Urgent'),
                    ('actively_looking', 'Actively Looking'),
                    ('passively_looking', 'Passively Looking'),
                    ('not_looking', 'Not Looking'),
                ],
                max_length=17,
            ),
        ),
        migrations.AddField(
            model_name='candidate',
            name='largest_management_scope',
            field=models.CharField(
                blank=True,
                choices=[
                    ('individual', 'Individual Contributor'),
                    ('team', 'Team'),
                    ('division', 'Division'),
                    ('country', 'Country'),
                    ('region', 'Region'),
                    ('global', 'Global'),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='candidate',
            name='notice_period',
            field=models.CharField(
                blank=True,
                choices=[
                    ('immediate', 'Immediate'),
                    ('two_weeks', '2 Weeks'),
                    ('one_month', '1 Month'),
                    ('two_months', '2 Months'),
                    ('three_months', '3+ Months'),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name='candidate',
            name='other_desired_benefits',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ('sign_on_bonus', 'One-Time Sign On Bonus'),
                        ('relocation', 'Relocation'),
                        ('holidays', 'Minimum Number of Holidays Per Year'),
                        ('schooling', 'Schooling for Kids'),
                        ('company_car', 'Company Car'),
                        ('training', 'Company Sponsored Training'),
                        ('housing', 'Housing Support'),
                        ('equity', 'Equity'),
                        ('tax_equalization', 'Tax Equalization'),
                        ('special_insurance', 'Special Insurance'),
                        ('other', 'Other'),
                    ],
                    max_length=17,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name='candidate',
            name='other_desired_benefits_others_detail',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='candidate',
            name='tax_equalization',
            field=models.BooleanField(null=True, blank=True),
        ),
        migrations.RemoveField(model_name='job', name='other_benefits',),
        migrations.AddField(
            model_name='job',
            name='other_benefits',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ('visa', 'Visa Sponsorship'),
                        ('relocation', 'Relocation Assistance'),
                        ('wellness', 'Gym / Wellness Membership'),
                        ('coffee', 'Free Coffee'),
                    ],
                    max_length=10,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.RemoveField(model_name='job', name='social_insurances',),
        migrations.AddField(
            model_name='job',
            name='social_insurances',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ('health', 'Health Insurance'),
                        ('employment', 'Employment Insurance'),
                        ('welfare_pension', 'Welfare Pension Insurance'),
                        (
                            'accident_compensation',
                            'Workers Accident Compensation Insurance',
                        ),
                    ],
                    max_length=21,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.CreateModel(
            name='CandidateCertification',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'certification',
                    models.CharField(
                        choices=[
                            ('toeic', 'TOEIC'),
                            ('jlpt', 'JLPT'),
                            ('toefl', 'TOEFL'),
                            ('other', 'Other Cerfication'),
                        ],
                        max_length=5,
                    ),
                ),
                ('certification_other', models.CharField(blank=True, max_length=32)),
                ('score', models.CharField(blank=True, max_length=16)),
                (
                    'candidate',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='certifications',
                        to='core.Candidate',
                    ),
                ),
            ],
        ),
    ]
