# Generated by Django 2.2.17 on 2021-02-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0220_candidate_new_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobappointmenttemplate', options={'ordering': ['order', 'pk']},
        ),
    ]
