# Generated by Django 2.2.17 on 2021-02-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0222_remove_candidate_field_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalstatus',
            name='group',
            field=models.CharField(
                choices=[
                    ('associated_to_job', 'Associated to Job'),
                    ('applied_by_candidate', 'Applied by Candidate'),
                    ('suitable', 'Suitable'),
                    ('contacted', 'Contacted'),
                    ('qualified', 'Qualified'),
                    ('submitted_to_hiring_manager', 'Submitted to Hiring Manager'),
                    ('to_be_scheduled', 'To Be Scheduled'),
                    (
                        'pending_candidate_confirmation',
                        'Pending Candidate Confirmation',
                    ),
                    ('confirmed_client_availability', 'Confirmed Client Availability'),
                    ('scheduled', 'Scheduled'),
                    ('completed_pending_feedback', 'Completed - Pending Feedback'),
                    ('pending_hiring_decision', 'Pending Hiring Decision'),
                    ('offer_to_be_prepared', 'Offer To Be Prepared'),
                    ('pending_offer_acceptance', 'Pending Offer Acceptance'),
                    ('pending_start', 'Pending Start'),
                    ('started', 'Started'),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name='proposalstatus',
            name='stage',
            field=models.CharField(
                choices=[
                    ('associated', 'Associated'),
                    ('pre_screening', 'Pre-Screening'),
                    ('screening', 'Screening'),
                    ('submissions', 'Submissions'),
                    ('interviewing', 'Interviewing'),
                    ('offering', 'Offering'),
                    ('hired', 'Hired'),
                ],
                max_length=32,
            ),
        ),
    ]
