# Generated by Django 2.2.17 on 2020-11-23 13:18

from django.db import migrations


# Note(ZOO-957): status - quick actions
STAGE_STATUS_ORG_QUICK_ACTION_MAPPING = {
    'associated': {
        'associated_to_job': {
            'client': [
                ('change_status', 'Suitable', 'associated', 'suitable',),
                ('reject', 'Reject Candidate', None, None),
            ],
            'agency': [
                (
                    'change_status',
                    'Submit to Client',
                    'submissions',
                    'submitted_to_hiring_manager',
                ),
                ('reject', 'Reject Candidate', None, None),
            ],
        },
        'applied_by_candidate': {
            'client': [
                ('change_status', 'Suitable', 'associated', 'suitable',),
                ('reject', 'Reject Candidate', None, None),
            ],
            'agency': [
                (
                    'change_status',
                    'Submit to Client',
                    'submissions',
                    'submitted_to_hiring_manager',
                ),
                ('reject', 'Reject Candidate', None, None),
            ],
        },
        'suitable': {
            'client': [
                ('change_status', 'Contacted', 'screening', 'contacted',),
                ('reject', 'Reject Candidate', None, None),
            ],
            'agency': [
                (
                    'change_status',
                    'Submit to Client',
                    'submissions',
                    'submitted_to_hiring_manager',
                ),
                ('reject', 'Reject Candidate', None, None),
            ],
        },
    },
    'screening': {
        'contacted': {
            'client': [
                ('change_status', 'Qualified', 'screening', 'qualified',),
                ('reject', 'Reject Candidate', None, None),
            ],
            'agency': [
                (
                    'change_status',
                    'Submit to Client',
                    'submissions',
                    'submitted_to_hiring_manager',
                ),
                ('reject', 'Reject Candidate', None, None),
            ],
        },
        'qualified': {
            'client': [
                (
                    'change_status',
                    'Submit to Hiring Manager',
                    'submissions',
                    'submitted_to_hiring_manager',
                ),
                ('reject', 'Reject Candidate', None, None),
            ],
            'agency': [
                (
                    'change_status',
                    'Submit to Client',
                    'submissions',
                    'submitted_to_hiring_manager',
                ),
                ('reject', 'Reject Candidate', None, None),
            ],
        },
    },
    'submissions': {
        'submitted_to_hiring_manager': {
            'client': [
                (
                    'change_status',
                    'Approved by Hiring Manager',
                    'interviewing',
                    'to_be_scheduled',
                ),
                ('reject', 'Rejected Candidate', None, None),
            ],
            'agency': [
                (
                    'change_status',
                    'Approved by Client',
                    'interviewing',
                    'to_be_scheduled',
                ),
                ('reject', 'Rejected by Client', None, None),
            ],
        },
    },
    'interviewing': {
        'to_be_scheduled': {
            'client': [
                ('schedule_interview', 'Schedule Interview', None, None),
                ('reject', 'Reject Candidate', None, None),
            ],
            'agency': [],
        },
        'pending_candidate_confirmation': {
            'client': [
                ('passed_interview', 'Passed Interview', None, None),
                ('reject', 'Reject Candidate', None, None),
            ],
            'agency': [
                ('schedule_interview', 'Schedule Interview', None, None),
                ('reject', 'Reject Candidate', None, None),
            ],
        },
        'confirmed_client_availability': {
            'client': [],
            'agency': [
                ('schedule_interview', 'Schedule Interview', None, None),
                ('reject', 'Reject Candidate', None, None),
            ],
        },
        'scheduled': {
            'client': [
                ('passed_interview', 'Passed Interview', None, None),
                ('reject', 'Reject Candidate', None, None),
            ],
            'agency': [
                ('passed_interview', 'Passed Interview', None, None),
                ('reject', 'Rejected by Client', None, None),
            ],
        },
        'completed_pending_feedback': {
            'client': [
                ('passed_interview', 'Passed Interview', None, None),
                ('reject', 'Reject Candidate', None, None),
            ],
            'agency': [
                ('passed_interview', 'Passed Interview', None, None),
                ('reject', 'Rejected by Client', None, None),
            ],
        },
    },
    'offering': {
        'pending_hiring_decision': {
            'client': [
                (
                    'change_status',
                    'Decided to Offer',
                    'offering',
                    'offer_to_be_prepared',
                ),
                ('reject', 'Reject Candidate', None, None),
            ],
            'agency': [
                ('change_status', 'Offer Accepted', 'hired', 'pending_start'),
                ('reject', 'Offer Declined', None, None),
            ],
        },
        'offer_to_be_prepared': {
            'client': [
                (
                    'change_status',
                    'Presented the Offer',
                    'offering',
                    'pending_offer_acceptance',
                ),
                ('reject', 'Reject Candidate', None, None),
            ],
            'agency': [
                ('change_status', 'Offer Accepted', 'hired', 'pending_start'),
                ('reject', 'Offer Declined', None, None),
            ],
        },
        'pending_offer_acceptance': {
            'client': [
                ('change_status', 'Offer Accepted', 'hired', 'pending_start'),
                ('reject', 'Reject Candidate', None, None),
            ],
            'agency': [
                ('change_status', 'Offer Accepted', 'hired', 'pending_start'),
                ('reject', 'Offer Declined', None, None),
            ],
        },
    },
}


def add_quick_actions(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    ProposalQuickAction = apps.get_model('core', 'ProposalQuickAction')
    ProposalStatus = apps.get_model('core', 'ProposalStatus')

    ProposalQuickAction.objects.using(db_alias).delete()
    for stage, status_dict in STAGE_STATUS_ORG_QUICK_ACTION_MAPPING.items():
        for status, org_dict in status_dict.items():
            for org_type, quick_action_tuple_list in org_dict.items():
                for action, label, to_stage, to_status in quick_action_tuple_list:
                    proposal_statuses = (
                        ProposalStatus.objects.using(db_alias)
                        .filter(stage=stage, group=status)
                        .all()
                    )
                    to_proposal_status = (
                        ProposalStatus.objects.using(db_alias)
                        .filter(stage=to_stage, group=to_status)
                        .first()
                    )
                    for proposal_status in proposal_statuses:
                        quick_action = ProposalQuickAction.objects.using(
                            db_alias
                        ).create(
                            proposal_status=proposal_status,
                            action=action,
                            org_type=org_type,
                            label_en=label,
                            to_proposal_status=to_proposal_status,
                        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0224_new_default_proposal_statuses'),
    ]

    operations = [migrations.RunPython(add_quick_actions, migrations.RunPython.noop)]
