# Generated by Django 2.2.17 on 2021-02-19 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0226_update_default_appointment_templates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppointmentTemplate', new_name='InterviewTemplate',
        ),
        migrations.RenameModel(
            old_name='JobAppointmentTemplate', new_name='JobInterviewTemplate',
        ),
        migrations.RenameModel(
            old_name='ProposalAppointment', new_name='ProposalInterview',
        ),
        migrations.RenameModel(
            old_name='ProposalAppointmentInvite', new_name='ProposalInterviewInvite',
        ),
        migrations.RenameModel(
            old_name='ProposalAppointmentTimeSlot',
            new_name='ProposalInterviewTimeSlot',
        ),
    ]
