# Generated by Django 2.2.17 on 2021-02-23 02:45

from django.db import migrations


GROUP_NAMES = [
    'Client Administrators',
    'Client Internal Recruiters',
    'Client Standard Users',
]


def add_user_groups(apps, schema_editor):
    """Create default Groups."""
    db_alias = schema_editor.connection.alias

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    groups = Group.objects.using(db_alias).bulk_create(
        [Group(name=group) for group in GROUP_NAMES]
    )


def delete_user_groups(apps, schema_editor):
    """Delete default Groups."""
    db_alias = schema_editor.connection.alias

    Group = apps.get_model('auth', 'Group')
    Group.objects.using(db_alias).filter(name__in=GROUP_NAMES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0229_add_client_roles'),
    ]

    operations = [migrations.RunPython(add_user_groups, delete_user_groups)]
