# Generated by Django 2.2.19 on 2021-03-04 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0230_add_client_profile_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalQuestion',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('text', models.CharField(max_length=1024)),
                ('answer', models.CharField(blank=True, max_length=1024)),
                (
                    'proposal',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='questions',
                        related_query_name='question',
                        to='core.Proposal',
                    ),
                ),
            ],
            options={'ordering': ('id',),},
        ),
    ]
