# Generated by Django 2.2.19 on 2021-03-04 06:37

from django.db import migrations


def add_proposal_questions(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Proposal = apps.get_model('core', 'Proposal')
    proposals = Proposal.objects.using(db_alias).all()
    ProposalQuestion = apps.get_model('core', 'ProposalQuestion')
    for proposal in proposals:
        for template in proposal.job.questions.all():
            ProposalQuestion.objects.using(db_alias).get_or_create(
                proposal=proposal, text=template.text,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0231_proposal_questions_answers'),
    ]

    operations = [
        migrations.RunPython(add_proposal_questions, migrations.RunPython.noop)
    ]
