# Generated by Django 2.2.19 on 2021-03-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0232_add_proposal_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='break_time_mins',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='paid_leaves',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='probation_period_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job', name='requirements', field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='telework_eligibility',
            field=models.CharField(
                blank=True,
                choices=[
                    ('onsite', 'On Site Only'),
                    ('possible', 'Remote Possible'),
                    ('remote', 'Remote Only'),
                ],
                default='onsite',
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_location',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
