# Generated by Django 2.2.19 on 2021-03-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0233_update_job_nullable_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatefile',
            name='title',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='jobfile',
            name='title',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
