# Generated by Django 2.2.19 on 2021-03-09 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0234_add_file_titles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job', options={'ordering': ('created_at',)},
        ),
    ]
