# Generated by Django 2.2.19 on 2021-03-12 10:27

from django.db import migrations


def update_existing_proposals(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Proposal = apps.get_model('core', 'Proposal')
    ProposalInterview = apps.get_model('core', 'ProposalInterview')
    proposals = Proposal.objects.using(db_alias).all()

    for proposal in proposals:
        if proposal.interviews.all():
            current_interview = proposal.interviews.filter(
                is_current_interview=True
            ).first()
            if not current_interview:
                interview = proposal.interviews.order_by('order').first()
                interview.is_current_interview = True
                interview.save()
        else:
            interview_templates = proposal.job.interview_templates.all()
            for template in interview_templates:
                ProposalInterview.objects.get_or_create(
                    proposal=proposal,
                    interview_type=template.interview_type,
                    order=template.order,
                    description=template.description,
                    interviewer=template.interviewer,
                    created_by=proposal.job.owner,
                    is_current_interview=(template.order == 1),
                )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0236_jobs_default_order_reversed'),
    ]

    operations = [
        migrations.RunPython(update_existing_proposals, migrations.RunPython.noop)
    ]
