# Generated by Django 2.2.19 on 2021-03-21 10:47

from django.db import migrations

NOTIFICATIONS_MAPPING = [
    'candidate_is_added_to_job',
    'candidate_is_added_to_job_direct_application',
    'candidate_is_added_to_job_excl_direct_application',
    'client_changed_proposal_status',
    'job_is_filled',
    'proposal_is_rejected',
]


def add_notification_settings(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Notification = apps.get_model('core', 'Notification')
    Notification.objects.using(db_alias).all().delete()
    NotificationSetting = apps.get_model('core', 'NotificationSetting')
    User = apps.get_model('core', 'User')

    for user in User.objects.using(db_alias).all():
        for notification_group in NOTIFICATIONS_MAPPING:
            NotificationSetting.objects.get_or_create(
                user=user, notification_type_group=notification_group,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0238_user_notification_settings'),
    ]

    operations = [
        migrations.RunPython(add_notification_settings, migrations.RunPython.noop)
    ]
