# Generated by Django 2.2.19 on 2021-03-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0240_update_candidate_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencedetail',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
