# Generated by Django 2.2.19 on 2021-03-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0241_add_experience_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='platform',
            field=models.CharField(
                blank=True,
                choices=[
                    ('linkedin', 'LinkedIn'),
                    ('facebook', 'Facebook'),
                    ('biz_reach', 'Biz Reach'),
                    ('github', 'Github'),
                    ('careercross', 'CareerCross'),
                    ('corporate_site', 'Corporate Website'),
                    ('other', 'Other'),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='candidate',
            name='platform_other_details',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='employment_status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('notemployed', 'Unemployed'),
                    ('fulltime', 'Permanent Employee'),
                    ('fixedterm', 'Fixed-term Contract Employee'),
                    ('temporary', 'Part-time Employee'),
                    ('businessowner', 'Business Owner'),
                    ('dispatched', 'Dispatched'),
                    ('freelance', 'Freelance'),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_experience',
            field=models.CharField(
                blank=True,
                choices=[
                    ('none', 'None'),
                    ('zero_one_year', '0-1 year'),
                    ('one_two_years', '1-2 years'),
                    ('two_five_years', '2-5 years'),
                    ('five_ten_years', '5-10 years'),
                    ('ten_plus_years', '10+ years'),
                ],
                default='none',
                max_length=16,
            ),
        ),
    ]
