# Generated by Django 2.2.19 on 2021-03-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0243_update_old_values'),
    ]

    operations = [
        migrations.AlterUniqueTogether(name='tag', unique_together=set(),),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(
                fields=('name', 'type', 'org_content_type', 'org_id'),
                name='unique tag by name type org',
            ),
        ),
    ]
