# Generated by Django 2.2.19 on 2021-03-31 06:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0244_change_tag_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAgreement',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'document_type',
                    models.CharField(
                        choices=[
                            ('tandc', 'Terms and Conditions'),
                            ('pp', 'Privacy Policy'),
                        ],
                        max_length=8,
                    ),
                ),
                ('version', models.PositiveIntegerField()),
                ('is_draft', models.BooleanField(default=False)),
                (
                    'file',
                    models.FileField(
                        max_length=256,
                        upload_to=core.models.get_legalagreement_upload_to,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_legal_agreed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='legal_agreement_hash',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='legalagreement',
            constraint=models.UniqueConstraint(
                fields=('document_type', 'version'),
                name='unique legal agreement type per version',
            ),
        ),
    ]
