# Generated by Django 2.2.19 on 2021-04-09 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0245_add_legal_agreements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(
                blank=True,
                choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')],
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='owner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='owned_candidates',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
