# Generated by Django 2.2.19 on 2021-04-10 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0246_candidate_fields_updates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='bonus_and_commissions',
            new_name='current_salary_variable',
        ),
        migrations.RemoveField(model_name='candidate', name='other_allowances',),
        migrations.RemoveField(model_name='candidate', name='rsu_and_options',),
    ]
