# Generated by Django 2.2.19 on 2021-04-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0247_candidate_salary_fields_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate', name='largest_management_scope',
        ),
        migrations.AddField(
            model_name='candidate',
            name='max_num_people_managed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
