# Generated by Django 2.2.19 on 2021-04-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0248_add_candidate_max_people_managed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposalinterview', options={'ordering': ('order',)},
        ),
        migrations.AlterField(
            model_name='proposalinterview',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposalinterview',
            name='order',
            field=models.PositiveIntegerField(
                db_index=True, editable=False, verbose_name='order'
            ),
        ),
        migrations.AlterField(
            model_name='proposalinterview',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
