# Generated by Django 2.2.19 on 2021-04-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0249_interview_order_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalinterview',
            name='status',
            field=models.CharField(
                choices=[
                    ('to_be_scheduled', 'To Be Scheduled'),
                    ('pending', 'Pending Candidate Confirmation'),
                    ('confirmed', 'Scheduled'),
                    ('rejected', 'To Be Rescheduled'),
                    ('canceled', 'Canceled'),
                    ('completed', 'Completed'),
                ],
                default='to_be_scheduled',
                max_length=15,
            ),
        ),
    ]
