# Generated by Django 2.2.19 on 2021-04-19 02:47

from django.db import migrations


def update_existing_interviews(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    ProposalInterview = apps.get_model('core', 'ProposalInterview')

    interviews = ProposalInterview.objects.using(db_alias).filter(
        start_at=None, end_at=None, status='pending'
    )
    interviews.update(status='to_be_scheduled')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0250_interview_new_status'),
    ]

    operations = [
        migrations.RunPython(update_existing_interviews, migrations.RunPython.noop)
    ]
