# Generated by Django 2.2.19 on 2021-04-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0253_update_notification_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalinterview',
            name='notes',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
