# Generated by Django 2.2.19 on 2021-04-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0255_add_interview_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalinterviewassessment',
            name='decision',
            field=models.CharField(
                choices=[
                    ('proceed', 'Proceed'),
                    ('keep', 'Keep'),
                    ('reject', 'Reject'),
                ],
                max_length=7,
            ),
        ),
    ]
