# Generated by Django 2.2.19 on 2021-05-04 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0256_update_assessment_decision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hiringcriterionassessment',
            old_name='interview',
            new_name='assessment',
        ),
    ]
