# Generated by Django 3.1.10 on 2021-05-07 07:07

import core.models
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0259_update_notification_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyregistrationrequest',
            name='headers',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='li_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='zoho_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidatelinkedindata', name='data', field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='zoho_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientregistrationrequest',
            name='headers',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='redux_state',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='zoho_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='context_data',
            field=models.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='frontend_settings',
            field=models.JSONField(
                default=core.models.FrontendSettingsSchema.get_default_frontend_settings
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='on_activation_params',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='zoho_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
