# Generated by Django 3.1.10 on 2021-05-25 05:34

from django.db import migrations

REASON_DECLINE_CANDIDATE_TEXTS = [
    {'text_en': 'Lack of Skill Match', 'text_ja': 'スキル不一致'},
    {'text_en': 'Lack of Experience Match', 'text_ja': '経験不一致'},
    {'text_en': 'Compensation Does Not Meet Expectations', 'text_ja': '待遇'},
    {'text_en': 'Misunderstood Job Description', 'text_ja': '仕事内容'},
    {'text_en': 'Misrepresented Career Background', 'text_ja': '経歴情報の不備'},
    {'text_en': 'Is Duplicate', 'text_ja': '重複レコード'},
]

REASON_NOT_INTERESTED_TEXTS = [
    {'text_en': 'Compensation Does Not Meet Expectations', 'text_ja': '待遇'},
    {'text_en': 'Accepted Other Offer', 'text_ja': '他社内定'},
    {'text_en': 'Personal Reasons', 'text_ja': '個人的理由'},
    {'text_en': 'Lack of Recruiter Follow-up', 'text_ja': 'リクルーターの能力不足'},
    {'text_en': 'Misunderstood Job Description', 'text_ja': '仕事内容'},
    {'text_en': 'Will Remain in Current Company', 'text_ja': '現職残留'},
]

OTHER = {
    'text': 'Other',
    'text_en': 'Other',
    'text_ja': 'その他',
    'has_description': True,
}


def generate_default_rejection_reasons(apps, schema_editor):
    ReasonDeclineCandidateOption = apps.get_model(
        'core', 'ReasonDeclineCandidateOption'
    )
    ReasonNotInterested = apps.get_model('core', 'ReasonNotInterestedCandidateOption')

    ReasonDeclineCandidateOption.objects.all().delete()
    ReasonNotInterested.objects.all().delete()

    for entry in REASON_DECLINE_CANDIDATE_TEXTS:
        ReasonDeclineCandidateOption.objects.get_or_create(**entry)

    for entry in REASON_NOT_INTERESTED_TEXTS:
        ReasonNotInterested.objects.get_or_create(**entry)

    ReasonDeclineCandidateOption.objects.get_or_create(**OTHER)
    ReasonNotInterested.objects.get_or_create(**OTHER)


OLD_REASON_DECLINE_CANDIDATE_TEXTS = [
    {'text_en': 'Did not match expectations', 'text_ja': '期待と一致しませんでした'},
    {'text_en': 'Too expensive', 'text_ja': '高過ぎ'},
    {'text_en': 'Concerns on fit', 'text_ja': 'フィット感'},
    {'text_en': 'Is Duplicate', 'text_ja': '重複レコード'},
]

OLD_REASON_NOT_INTERESTED_TEXTS = [
    {'text_en': 'Not looking for a Job', 'text_ja': '転職を考えていません'},
    {'text_en': 'Not interested in Company', 'text_ja': '会社に興味ありません'},
    {'text_en': 'Not interested in Role', 'text_ja': 'ロールに興味ありません'},
    {'text_en': 'Salary expectation don\'t match', 'text_ja': '希望通りの給与ではありません'},
    {'text_en': 'Cannot relocate', 'text_ja': '転勤できません'},
]


def revert_rejection_reasons(apps, schema_editor):
    ReasonDeclineCandidateOption = apps.get_model(
        'core', 'ReasonDeclineCandidateOption'
    )
    ReasonNotInterested = apps.get_model('core', 'ReasonNotInterestedCandidateOption')

    ReasonDeclineCandidateOption.objects.all().delete()
    ReasonNotInterested.objects.all().delete()

    for entry in OLD_REASON_DECLINE_CANDIDATE_TEXTS:
        ReasonDeclineCandidateOption.objects.get_or_create(**entry)

    for entry in OLD_REASON_NOT_INTERESTED_TEXTS:
        ReasonNotInterested.objects.get_or_create(**entry)

    ReasonDeclineCandidateOption.objects.get_or_create(**OTHER)
    ReasonNotInterested.objects.get_or_create(**OTHER)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0261_update_notifications_verbs'),
    ]

    operations = [
        migrations.RunPython(
            generate_default_rejection_reasons, revert_rejection_reasons
        ),
    ]
