# Generated by Django 3.1.10 on 2021-06-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0264_updated_proposal_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalstatus',
            name='group',
            field=models.CharField(
                choices=[
                    ('associated_to_job', 'Associated to Job'),
                    ('applied_by_candidate', 'Applied by Candidate'),
                    ('suitable', 'Suitable'),
                    ('contacted', 'Contacted'),
                    ('qualified', 'Qualified'),
                    ('submitted_to_hiring_manager', 'Submitted to Hiring Manager'),
                    ('interviewing', 'Interviewing'),
                    ('pending_hiring_decision', 'Pending Hiring Decision'),
                    ('offer_to_be_prepared', 'Offer To Be Prepared'),
                    ('pending_offer_acceptance', 'Pending Offer Acceptance'),
                    ('pending_start', 'Pending Start'),
                    ('started', 'Started'),
                ],
                max_length=64,
            ),
        ),
    ]
