# Generated by Django 3.1.10 on 2021-06-04 07:01

from django.db import migrations


def make_recruiter_many(apps, schema_editor):
    Job = apps.get_model('core', 'Job')
    for job in Job.objects.filter(recruiter__isnull=False):
        job.recruiters.add(job.recruiter)


def make_recruiters_single(apps, schema_editor):
    Job = apps.get_model('core', 'Job')
    for job in Job.objects.filter(recruiters__isnull=False):
        job.recruiter = job.recruiters.first()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0266_add_job_recruiters_field'),
    ]

    operations = [migrations.RunPython(make_recruiter_many, make_recruiters_single)]
