# Generated by Django 3.1.10 on 2021-06-08 05:01

from django.db import migrations

DEFAULT_FRONTEND_SETTINGS = {
    'dashboard_jobs_show_per': 50,
    'dashboard_proposals_show_per': 50,
    'jobs_show_per': 50,
    'jobs_shortlist_show_per': 50,
    'jobs_longlist_show_per': 50,
    'candidates_show_per': 50,
    'organizations_show_per': 50,
    'agency_directory_show_per': 50,
    'staff_show_per': 50,
    'notifications_show_per': 50,
    'agency_proposals_show_per': 50,
    'client_jobs_show_per': 50,
    'submit_candidates_show_per': 50,
    'proposals_snapshot_show_per': 50,
    'assign_members_show_per': 50,
    'deal_pipeline_candidates_show_per': 50,
    'job_import_longlist_show_per': 50,
    'candidate_placements_show_per': 50,
}

OLD_FRONTEND_SETTINGS = {
    'dashboard_jobs_show_per': 5,
    'dashboard_proposals_show_per': 5,
    'jobs_show_per': 5,
    'jobs_shortlist_show_per': 5,
    'jobs_longlist_show_per': 5,
    'candidates_show_per': 5,
    'organizations_show_per': 5,
    'agency_directory_show_per': 5,
    'staff_show_per': 5,
    'notifications_show_per': 5,
    'agency_proposals_show_per': 5,
    'client_jobs_show_per': 5,
    'submit_candidates_show_per': 5,
    'proposals_snapshot_show_per': 5,
    'assign_members_show_per': 5,
    'deal_pipeline_candidates_show_per': 5,
    'job_import_longlist_show_per': 5,
    'candidate_placements_show_per': 5,
}


def update_frontend_settings(apps, schema_editor):
    User = apps.get_model('core', 'User')
    User.objects.all().update(frontend_settings=DEFAULT_FRONTEND_SETTINGS)


def revert_frontend_settings(apps, schema_editor):
    User = apps.get_model('core', 'User')
    User.objects.all().update(frontend_settings=OLD_FRONTEND_SETTINGS)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0268_remove_job_recruiter_field'),
    ]

    operations = [
        migrations.RunPython(update_frontend_settings, revert_frontend_settings)
    ]
