# Generated by Django 3.1.13 on 2021-08-26 14:33

import django.contrib.admin.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('core', '0270_client_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[],
            options={
                'verbose_name': 'log entry',
                'verbose_name_plural': 'log entries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin.logentry',),
            managers=[('objects', django.contrib.admin.models.LogEntryManager()),],
        ),
    ]
