# Generated by Django 3.1.13 on 2021-08-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0272_update_job_to_multi_table'),
    ]

    operations = [
        migrations.RemoveField(model_name='job', name='public_uuid',),
        migrations.AddField(
            model_name='careersitejobposting',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='privatejobposting',
            name='public_uuid',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
    ]
