# Generated by Django 3.1.13 on 2021-09-22 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0274_add_client_career_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='careersitejobposting',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='careersitejobposting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='privatejobposting',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privatejobposting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
