# Generated by Django 3.1.13 on 2021-10-04 05:08

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0276_add_meta_fields_to_organizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='logo',
            field=models.FileField(
                blank=True,
                help_text='png, svg',
                null=True,
                upload_to=core.models.get_agency_logo_upload_to,
                validators=[core.models.validate_file_image],
            ),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cv_ja_thumbnail',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=core.models.get_cv_ja_thumbnail_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume_ja_thumbnail',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=core.models.get_resume_ja_thumbnail_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume_thumbnail',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=core.models.get_resume_thumbnail_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name='candidatefile',
            name='thumbnail',
            field=models.FileField(
                upload_to=core.models.get_candidate_file_thumbnail_path
            ),
        ),
        migrations.AlterField(
            model_name='jobfile',
            name='thumbnail',
            field=models.FileField(
                blank=True, upload_to=core.models.get_jobfile_thumbnail_upload_to
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(
                blank=True, null=True, upload_to=core.models.get_user_photo_upload_to
            ),
        ),
    ]
