# Generated by Django 3.1.13 on 2021-10-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0277_remove_public_storage_from_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalinterviewschedule',
            name='pre_schedule_msg',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
