# Generated by Django 3.1.13 on 2021-10-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0279_add_skipped_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalinterviewschedule',
            name='scheduling_type',
            field=models.CharField(
                choices=[
                    (
                        'interview_proposal',
                        'Interview Proposal (Send interview time slots to Candidate)',
                    ),
                    (
                        'simple_scheduling',
                        'Simple Scheduling (Candidate has been invited outside ZooKeep)',
                    ),
                    (
                        'past_scheduling',
                        'Past Scheduling (Record an interview that already took place)',
                    ),
                ],
                max_length=20,
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name='proposalinterview',
            name='current_schedule',
            field=models.ForeignKey(
                null=True,
                on_delete=models.deletion.RESTRICT,
                related_name='default_for_interviews',
                to='core.proposalinterviewschedule',
            ),
        ),
    ]
