# Generated by Django 3.1.13 on 2021-10-20 15:03

from django.db import migrations


def rename_direct_apply_source(apps, schema_editor):
    Candidate = apps.get_model('core', 'Candidate')
    Candidate.objects.filter(source='Applicants (Direct)').update(source='Direct Apply')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0281_set_default_scheduling_type'),
    ]

    operations = [
        migrations.RunPython(rename_direct_apply_source, migrations.RunPython.noop),
    ]
