# Generated by Django 3.1.13 on 2021-11-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0282_rename_to_direct_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalinterview',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
