# Generated by Django 3.1.13 on 2021-10-20 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0283_unlimit_interview_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_note_activities', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_activities', to='core.candidate')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_activities', to='core.job')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_activities', to='core.proposal')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='noteactivity',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('candidate__isnull', False), ('job__isnull', False), ('proposal__isnull', False)), models.Q(('proposal__isnull', True), models.Q(models.Q(('candidate__isnull', True), ('job__isnull', False)), models.Q(('candidate__isnull', False), ('job__isnull', True)), _connector='OR')), _connector='OR'), name='core_noteactivity_enforce_relations'),
        ),
    ]
