# Generated by Django 3.1.13 on 2021-10-31 11:51

from django.db import migrations, models


NEW_NOTIFICATION_SETTING = 'note_activity_added_to_proposal'

def update_notification_settings(apps, schema_editor):
    User = apps.get_model('core', 'User')
    for user in User.objects.all():
        user.notification_settings.create(notification_type_group=NEW_NOTIFICATION_SETTING)


def revert_notification_settings(apps, schema_editor):
    NotificationSetting = apps.get_model('core', 'NotificationSetting')
    NotificationSetting.objects.filter(notification_type_group=NEW_NOTIFICATION_SETTING).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0284_add_note_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('agency_assigned_member_for_job', 'Your agency assigns you to a job'), ('candidate_longlisted_for_job', 'Candidate longlisted for a job'), ('candidate_shortlisted_for_job', 'Candidate shortlisted for a job'), ('client_assigned_agency_for_job', 'Client assigns your agency to a job'), ('client_changed_proposal_status', 'Application Status is Updated'), ('client_created_contract', 'Client creates a contract with your agency'), ('client_updated_job', 'Client updates a job'), ('contract_initiated_agency', 'Your contract with the client has been initiated.'), ('contract_initiated_client', 'Your contract with the agency has been initiated.'), ('contract_invitation_accepted', 'Agency accepted invitation'), ('contract_invitation_declined', 'Agency declined invitation'), ('contract_job_access_revoked_invite_ignored', 'Job access has been removed'), ('contract_job_access_revoked_no_agreement', 'Job access has been removed'), ('contract_signed_by_one_party', 'Contract is signed by one of the parties'), ('fee_approved', 'Fee is approved'), ('fee_draft', 'Fee is set as draft'), ('fee_needs_revision', 'Fee is sent to revision'), ('fee_pending', 'Fee is submitted for approval'), ('fee_pending_reminder', 'Fee is waiting approval'), ('interview_assessment_added_interviewer', 'Interview assessment is added'), ('interview_assessment_added_recruiter', 'Interview assessment is added'), ('interview_proposal_canceled', 'Proposal interview canceled'), ('interview_proposal_confirmed_interviewer', 'Proposal interview confirmed'), ('interview_proposal_confirmed_proposer', 'Interview Proposal is Confirmed by Candidate'), ('interview_proposal_is_sent', 'Interview Proposal is Sent to Candidate'), ('interview_proposal_rejected_interviewer', 'Proposal interview rejected'), ('interview_proposal_rejected_recruiter', 'Proposal interview rejected'), ('job_is_filled', 'Job is Filled up'), ('new_proposal_candidate_direct_application', 'Candidate is Added to Job - Direct Application'), ('new_proposal_candidate_recruiter', 'Candidate is Added to Job (excl. Direct Application)'), ('new_proposal_candidate_sourced_by', 'Candidate is Added to Job'), ('note_activity_added_to_proposal', 'A new note is added to an application'), ('placement_fee_approved', 'Candidate placement is approved'), ('placement_fee_draft', 'Candidate placement is set as draft'), ('placement_fee_needs_revision', 'Candidate placement is sent to revision'), ('placement_fee_pending', 'Candidate placement is submitted for approval'), ('placement_fee_pending_reminder', 'Candidate placement is sent to revision'), ('proposal_approved_rejected_by_hiring_manager', 'N/A'), ('proposal_is_rejected', 'Application is Rejected'), ('proposal_moved', 'Candidate is reallocated to a different job'), ('proposal_pending_hiring_decision', 'N/A'), ('proposal_pending_start', 'N/A'), ('proposal_submitted_to_hiring_manager', 'N/A'), ('talent_assigned_manager_for_job', 'Talent Associate assigns you to a job'), ('user_mentioned_in_comment', 'User is mentioned'), ('user_mentioned_in_comment_deleted', 'Comment mentioning user is deleted')], max_length=255),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='notification_type_group',
            field=models.CharField(choices=[('candidate_is_added_to_job', 'Candidate is Added to Job'), ('candidate_is_added_to_job_direct_application', 'Candidate is Added to Job - Direct Application'), ('candidate_is_added_to_job_excl_direct_application', 'Candidate is Added to Job (excl. Direct Application)'), ('client_changed_proposal_status', 'Application Status is Updated'), ('interview_assessment_is_added', 'Interview assessment is added'), ('interview_proposal_is_confirmed', 'Interview Proposal is Confirmed by Candidate'), ('interview_proposal_is_sent', 'Interview Proposal is Sent to Candidate'), ('job_is_filled', 'Job is Filled up'), ('note_activity_added_to_proposal', 'A new note is added to an application'), ('proposal_is_rejected', 'Application is Rejected')], max_length=255),
        ),
        migrations.RunPython(update_notification_settings, revert_notification_settings)
    ]
